bower.json
main.scss
partials/submit.html
tests/partials/submit.spec.js

Adding submit button and styles

---

partials/company-name.html
partials/job-title.html
tests/partials/company-name.spec.js
tests/partials/job-title.spec.js

Adding new form fields for b2b forms

---

partials/email.html
partials/phone.html
tests/partials/email.spec.js
tests/partials/phone.spec.js

For b2b forms labels need to be editable

---

partials/firstname.html
partials/lastname.html

Removing descriptions as I don't believe they're needed

---

partials/firstname.html
partials/lastname.html

Labels are not title case

---

Makefile
README.md
partials/fieldset.html

Improving readme

---

main.scss
partials/accept-terms.html
partials/email.html
partials/fieldset.html
partials/phone.html
partials/section.html
partials/submit.html
tests/partials/accept-terms.spec.js
tests/partials/email.spec.js
tests/partials/phone.spec.js
tests/partials/section.spec.js
tests/partials/submit.spec.js

Adding b2b options and partials

---

partials/cookie-privacy.html
tests/partials/cookie-privacy.spec.js

Adding cookie privacy messaging

---

partials/accept-terms.html
tests/partials/accept-terms.spec.js

Fixing the copy described in the ticket
https://trello.com/c/pn9p7c8a/582-tcs-mistakes

Copy missing and mistakes

---

README.md
package.json
tests/utils/event-notifier.spec.js
utils/event-notifier.js

Centralise logic for embedded forms notifying parent frames via postmessage of height changes.
🐿 v2.8.0

EventNotifier work

---

partials/accept-terms.html

Fix typos with the print T&Cs
🐿 v2.8.0

Fix T&Cs Typos

---

partials/package-change.html

🐿 v2.10.3
Fixes up the `package-change` component to work with `next-subscribe`.
https://trello.com/c/ZpNdya65/537-select-package-component-top-bar

Remove class and add form method

---

utils/event-notifier.js

All manual triggering of the event-notifier

Add ability to manually notify

---

bower.json
demos/app.js
demos/data.json
main.scss
partials/progress-indicator.html

Adds the progress indicator component.
**NB**: The Origami team are going to be building their own version of this sometime in the near future so this doesn't have to be perfect just yet (looking at you sass nesting).
https://trello.com/c/bSZtb3OH/535-progress-indicator-component

Progress Indicator

---

tests/utils/tracking.spec.js
utils/tracking.js

Utility for firing o-tracking events. Features:
- Custom event firing
- Image event fallback
- Debug data added to window object
https://trello.com/c/TpAZiMXn/613-o-tracking-utility-in-n-conversion-forms

Tracking utility

---

partials/progress-indicator.html
tests/partials/progress-indicator.spec.js

Adds unit tests for the basic functionality in the component. 
Also adds changes the status from a string to two booleans. Hopefully this will make it clearer what statuses their are but also means classes aren't programmatically created and easier to find later.

Unit tests plus boolean status

---

partials/form.html
tests/partials/form.spec.js

It may seem like a small silly partial but it means we have complete separation of code from our applications and `ncf` as it means we don't need to hard code the `ncf` class into our applications.

Form partial

---

tests/utils/tracking.spec.js
utils/tracking.js

Pass event data as detail in CustomEvent, also wrote a test so this should never happen again!

Pass event data as detail in CustomEvent

---

demos/data.json
main.scss
partials/progress-indicator.html
tests/partials/progress-indicator.spec.js

🐿 v2.10.3
Realised that you shouldn't be able to click to navigate to anything that isn't completed. Also fixed the demo to use the new boolean states.

Tidy and fix up progress-indicator

---

partials/cookie-privacy.html

Unmasking is now Guest Pass
https://trello.com/c/pm8evRp6/674-rebranding-unmasking-guest-pass

Updating cookie terms to reference guest pass

---

utils/event-notifier.js

🐿 v2.10.3
Addresses https://sentry.io/nextftcom/ft-next-corp-signup/issues/686406371

Fix TypeError in event-notifier

---

main.scss

Super magic numbery, but hopefully will be take over by origami soon

Removes a slight gap at some screen sizes

---

Makefile
demos/data.json
main.scss
partials/confirmation.html
partials/package-change.html
secret-squirrel.js
tests/partials/confirmation.spec.js
tests/partials/package-change.spec.js

Somewhat controversially I put the whole page as a partial in here. My thinking was there is no point splitting it up as it may only be used once so I put it where the styles live. This is the first iteration to get it into the journey, there are spacing and font issues that can be addressed later during a design review.
https://trello.com/c/FYWX0YfF/516-buy-flow-confirmation-page

Confirmation page

---

partials/country.html
partials/delivery-country.html
tests/partials/delivery-country.spec.js

Enable delivery-countries partial to be auto-populated with countries
🐿 v2.8.0

Populate delivery-countries

---

partials/country.html
partials/delivery-country.html
partials/industry.html
partials/position.html
partials/responsibility.html
tests/partials/country.spec.js
tests/partials/delivery-country.spec.js
tests/partials/industry.spec.js
tests/partials/position.spec.js
tests/partials/responsibility.spec.js

Add empty first option to select inputs to make it clearer they're not pre-selected
🐿 v2.8.0

Add empty select option prompts

---

partials/company-name.html
partials/country.html
partials/delivery-country.html
partials/email.html
partials/firstname.html
partials/industry.html
partials/job-title.html
partials/lastname.html
partials/password.html
partials/phone.html
partials/position.html
partials/postcode.html
partials/responsibility.html
partials/submit.html
tests/helpers.js
tests/partials/company-name.spec.js
tests/partials/country.spec.js
tests/partials/delivery-country.spec.js
tests/partials/email.spec.js
tests/partials/firstname.spec.js
tests/partials/industry.spec.js
tests/partials/job-title.spec.js
tests/partials/lastname.spec.js
tests/partials/password.spec.js
tests/partials/phone.spec.js
tests/partials/position.spec.js
tests/partials/post-code.spec.js
tests/partials/responsibility.spec.js
tests/partials/submit.spec.js

🐿 v2.10.3
Allows fields to be disabled. Also slightly reformatted to make the templates easier to read.

Allow disabling of fields

---

demos/data.json
partials/message.html
tests/partials/message.spec.js

Allow o-message actions to be used in the message component

---

bower.json
main.scss
partials/message.html
tests/partials/message.spec.js

🐿 v2.10.3
Best reviewed [without whitespaces](https://github.com/Financial-Times/n-conversion-forms/pull/54/files?w=1)

Bump o-message and enable more styles/themes

---

partials/delivery-country.html
partials/form.html

Validation in `next-subscribe` expects this field to be `deliveryCountry` not `delivery-country`. I'm updating the form itself rather than the validation, as all the other fields are camel case so this is consistent

Update delivery country

---

package.json

Bump n-common-static-data to pull in latest country changes
🐿 v2.10.3

Bump common-static-data to 1.6.1

---

partials/billing-country.html
tests/partials/billing-country.spec.js

Separate billing, delivery + country

---

tests/utils/email.spec.js
utils/email.js

🐿 v2.10.3
The SDK response now just returns `true` or `false`.

Fix the check for the email exists check since the response has changed

---

partials/payment-term-selector.html
tests/partials/payment-term-selector.spec.js

Agreed with Aislinn and Lucinda that we don't need to vary payment term t+c wording based on package so updating to one agreed set of copy.

update t and c wording

---

utils/apple-pay.js
utils/email.js
utils/password.js
utils/tracking.js
utils/validation.js

Changing our document blocks case the parameters and returns correctly

Properly casing param objects

---

tests/utils/apple-pay.spec.js
utils/apple-pay.js

How embarrassing, thought I fixed an issue with the statics being used in statics, although this would work. The actual issue was in the method to methods change I hadn't covered all and the tests did not pick this up. Improved tests and made the change.

Methods not method

---

demos/views/index.html

Gives a handy link for each partial to link through to the page that only contains that component.

Provide a link to the partial for quicker testing

---

utils/payment-type.js

Fix Direct Debit payment type string

---

tests/utils/payment-type.spec.js
utils/payment-type.js

Adding a onChange helper method for the paymentType utility.

Add onChange helper to paymentType

---

partials/confirmation.html

Update the `Start exploring` link
https://trello.com/c/KqN45OGs/862-5-confirmation-page-onward-user-journey-when-buy-flow-completed

Update link to the newsletters page on confirmation page

---

main.scss
partials/confirmation.html
tests/partials/confirmation.spec.js

Updated design with Lucinda's help
https://trello.com/c/RBa9tkWU/819-8-buy-flow-confirmation-page

Design changes for confirmation form

---

bower.json
partials/debug.html
tests/partials/debug.spec.js

🐿 v2.12.3
Realised these were pretty pointless while testing the PROD apis.

Only add CC helpers in test

---

README.md
tests/utils/submit.spec.js
utils/submit.js

In order to allow text on the submit button to be dynamically updated 🐿 v2.12.3
https://trello.com/c/G4VNkcM8
https://trello.com/c/zx00FXFh
Linked to https://github.com/Financial-Times/next-subscribe/pull/233

Create submit button util

---

demos/data.json
partials/debug.html
tests/partials/debug.spec.js

This will be used to provide a link to the debug section in `next-subscribe`
https://trello.com/c/xVc7RwxM/843-5-buy-flow-error-message-review

 Add the ability to pass links into the debug partial

---

tests/utils/submit.spec.js
utils/submit.js

🐿 v2.12.3
https://trello.com/c/0xuGAx9L/1074-loaders-on-all-the-pages

Add enable/disable to submit util

---

README.md
tests/utils/submit.spec.js
utils/submit.js

🐿 v2.12.3
https://trello.com/c/0xuGAx9L/1074-5-loaders-on-all-the-pages

Add isDisabled helper method to Submit button util

---

main.scss
partials/package-change.html

Wow @lucindamaria is good!
https://trello.com/c/bQhmK5yw/1112-1-wrong-font-weight
| --- | --- |
| <img width="390" alt="Screenshot 2019-04-29 at 17 45 23" src="https://user-images.githubusercontent.com/1721150/56912281-dd371200-6aa6-11e9-90a4-90a301963ddb.png"> | <img width="403" alt="Screenshot 2019-04-29 at 17 46 41" src="https://user-images.githubusercontent.com/1721150/56912284-e0320280-6aa6-11e9-9468-9656e74278e6.png"> |

Use semibold for package change strong text

---

styles/loader.scss

🐿 v2.12.3
Request from UX to fix the font size.
https://trello.com/c/0xuGAx9L/1074-5-loaders-on-all-the-pages
|Before|After|
|-|-|
|<img src="https://user-images.githubusercontent.com/708296/56957874-736b4680-6b40-11e9-8657-c748be8a620e.png">|<img src="https://user-images.githubusercontent.com/708296/56957883-7c5c1800-6b40-11e9-84e7-d105e5082cce.png">|

Tweak loader content font size

---

tests/utils/payment-term.spec.js
utils/payment-term.js

Needed for payment term analytics

Add onChange method for payment term

---

partials/submit.html
tests/partials/submit.spec.js

Need to link to the submit button in an error message

Add id parameter for targeting

---

partials/confirmation.html

Asked for by legal
https://trello.com/c/Uj6sPVGo/1184-legal-tweak-on-confirmation-pages

Add the terms on the confirmation page

---

demos/data.json
main.scss
partials/confirmation.html
tests/partials/confirmation.spec.js

This is needed for the trail billing information
https://trello.com/c/StP7bWif/1181-bug-confirmation-page

Add ability to give a description to the confirmation definition list

---

partials/province.html
tests/partials/province.spec.js

Add partial for displaying canadian provinces eh

---

utils/postcode.js
utils/province.js
utils/state.js

Took the decision to forgo tests as it should be covered in the FormElement tests

Add helper classes for postcode, province and state

---

partials/postcode.html
partials/province.html
partials/state.html
tests/helpers.js
tests/partials/postcode.spec.js
tests/partials/province.spec.js
tests/partials/state.spec.js
tests/utils/form-element.spec.js
utils/form-element.js
utils/postcode.js
utils/province.js
utils/state.js

* Add ability to hide partials on render
* Add disable and enable to the form element utility
* Add billing option for state, postcode and province

Billing fields

---

tests/utils/form-element.spec.js
utils/form-element.js

We need to find the value of the form element
https://trello.com/c/e4KJFoBU/1216-paypal-payments-from-usa-and-can-are-hitting-payment-issues

Find the value from the input or select from form element

---

bower.json
styles/loader.scss
tests/helpers/ncf-countries.spec.js

Bump o-forms and o-loading to fix dependency resolution issues

---

docs/PARTIALS.md
partials/lastname.html

Update lastname placeholder and add documentation

---

partials/accept-terms.html

🐿 v2.12.3
lower cases `Contact`
https://trello.com/c/QdvkdRoV/1249-1-remove-terms-and-conditions-header-and-lower-case-contact
New:
Old:

lower cases contact

---

docs/PARTIALS.md

Add missing docs
https://trello.com/c/4TF5i1lD/1244-1-change-phone-number-form-field-title

Add phone partial documentation

---

docs/PARTIALS.md

https://trello.com/c/FHqhrzXF/1248-1-change-to-the-submit-button-text

Add documentation for the submit partial

---

demos/data.json
docs/PARTIALS.md
main.scss
partials/decision-maker.html
tests/partials/decision-maker.spec.js

https://trello.com/c/1e9Ap35M/1246-3-add-marketo-radio-button-functionality

Add decision maker field for b2b forms

---

main.scss
partials/decision-maker.html

Slight style tweak to align this to the end of the grid

Align decision maker radio group to the end of the grid

---

docs/PARTIALS.md

Forgot to add this from my last PR

Add payment term documentation

---

partials/debug.html
tests/partials/debug.spec.js

Ever landed on the signup forms in the wrong environment?
Then opened a tab, typed toggler.ft.com, found the sandbox flag, toggled it, then closed the tab?
NO MORE!

Add environment switcher to improve our lives

---

utils/validation.js

Debounce custom validation.

---

partials/debug.html

add postCode to helper for use on Details page for print journey

---

partials/delivery-option.html
partials/payment-term.html

🐿 v2.12.4
Pointed out by @liamkeaton [here](https://github.com/Financial-Times/n-conversion-forms/pull/210#pullrequestreview-260070255). It wasn't used.

Remove redundant class name

---

README.md

🐿 v2.12.3
add field autocomplete doc
https://trello.com/c/KKuwfoFG/1329-3-submit-payment-form
n/a

add field autocomplete doc

---

partials/billing-country.html

🐿 v2.12.3
change billingCountry id from kebab-case to camelCase
https://trello.com/c/KKuwfoFG/1329-3-submit-payment-form

change billingCountry id from kebab-case to camelCase

---

utils/validation.js

🐿 v2.12.4
This was far too lenient and ended up causing an infinite loop.

Bump validation debounce timer

---

partials/app-banner.html

🐿 v2.12.3
This ensures that the app banner has the correct font specifications
OLD:
NEW:

Adds div with ncf class

---

partials/delivery-instructions.html

🐿 v2.12.3
change note for delivery instructions
[Ticket](https://trello.com/c/spmwPga5/1420-1-change-note-for-delivery-instructions)
| ![image](https://user-images.githubusercontent.com/6513313/62623953-ed6a5300-b919-11e9-9244-e547e1821813.png) |  ![image](https://user-images.githubusercontent.com/6513313/62623976-fbb86f00-b919-11e9-90af-bbf8fd7b95a6.png)  |

change copy for delivery instructions note

---

demos/app.js
demos/data.json
partials/app-banner.html
partials/decision-maker.html
partials/email.html
partials/payment-type.html
partials/trial-banner.html
test/smoke.js

A11Y issues were being released into our forms, this will run pa11y tests on each template partial to catch them early.
Also fixed the issues that exist already.

Add pa11y testing to all partial URLs

---

partials/payment-term.html
test/partials/payment-term.spec.js

Make these consistent with the current signup form

Update payment term names

---

partials/registration-confirmation.html
test/partials/registration-confirmation.spec.js

Adding confirmation page for our registration journey

Add registration confirmation page

---

partials/debug.html

🐿 v2.12.4
Just had this thought after a discussion with Krum from the Membership team the other day. They were clearing out a bunch of test accounts in prod and they'd found a bunch of test email addresses I had created, but only because I had my name in them.

Use system code in debug email address

---

.github/PULL_REQUEST_TEMPLATE.md

🐿 v2.12.4
Pulled this across from the one in `next-subscribe`.

Update PR template to match `next-subscribe`

---

partials/debug.html

Setting fields programmatically does not fire a change event which we use to run functionality, trigger this manually.

On filling the form trigger events so functionality runs

---

partials/delivery-start-date.html

🐿 v2.12.4
[Ticket](https://trello.com/c/ibewnyrP/1567-delivery-start-date-make-it-clear-this-is-for-print)

Specify the delivery start date is for print

---

components/__snapshots__/password.spec.js.snap
components/password.jsx
components/password.spec.js
package.json

🐿 v2.12.4
Port the password partial to JSX
[Ticket](https://trello.com/c/QiBYvIZx/90-personal-details-port-password-to-jsx)

feat: port password partial to component

---

partials/delivery-instructions.html

[Ticket](https://trello.com/c/diHVkTZ0/1584-delivery-amends-print)

Updating the delivery instructions

---

partials/billing-postcode.html
partials/delivery-postcode.html
partials/email.html
partials/firstname.html
partials/lastname.html
partials/phone.html
test/partials/email.spec.js

get handlebars fixes and changes from jsx-poc branch onto master
https://trello.com/c/BkI3lPew/107-get-handlebars-fixes-and-changes-from-jsx-poc-branch-onto-master
The confirmation email is not used anywhere so it's been removed.

fix some dom issues and swap order of some params

---

partials/delivery-instructions.html

🐿 v2.12.4
`Packer` -> `Place`
[Ticket](https://trello.com/c/1mo0lfwH/1607-spelling-error#)

Fix spelling error

---

partials/confirmation.html

The newsletters page seems to be broken so send users to the homepage.
[Ticket](https://trello.com/c/VomYejer/1618-start-exploring-link-broken)

Change link for start exploring to the homepage

---

partials/delivery-instructions.html

[Ticket](https://trello.com/c/nfvXJCjt/1624-slight-copy-change)

Update delivery instructions copy

---

components/__snapshots__/submit.spec.js.snap
components/index.jsx
components/submit.jsx
components/submit.spec.js
demos/init-jsx.js

This PR creates a **Submit** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.

Add Submit JSX component

---

components/index.jsx
demos/init-jsx.js

**Industry**, **JobTitle**, and **Position** JSX components had not been added to the demos, which is corrected by this PR.

Add Industry, JobTitle, + Position components to demos

---

components/__snapshots__/form.spec.js.snap
components/form.jsx
components/form.spec.js
components/index.jsx
demos/init-jsx.js

This PR creates a **Form** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.

Add Form JSX component

---

components/__snapshots__/fieldset.spec.js.snap
components/fieldset.jsx
components/fieldset.spec.js
components/index.jsx
demos/init-jsx.js

This PR creates a **Fieldset** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.

Add Fieldset JSX component

---

partials/country.html
test/partials/country.spec.js

[Ticket](https://trello.com/c/4PqzB8p7/1637-change-country-field-on-b2b-forms-to-country-region)

Update country field for B2B 🐿 v2.12.5

---

components/__snapshots__/continue-reading.spec.js.snap
components/continue-reading.jsx
components/continue-reading.spec.js
components/index.jsx
demos/init-jsx.js

This PR creates a **Continue Reading** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.

Add Continue Reading JSX component

---

components/__snapshots__/customer-care.spec.js.snap
components/customer-care.jsx
components/customer-care.spec.js
components/index.jsx
demos/init-jsx.js

This PR creates a **Customer Care** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.

Add Customer Care JSX component

---

components/__snapshots__/accept-terms.spec.js.snap
components/accept-terms.jsx
components/accept-terms.spec.js
components/confirmation.jsx
components/index.jsx
demos/init-jsx.js
partials/accept-terms.html

This PR creates an **Accept Terms** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.

Add Accept Terms JSX component

---

components/__snapshots__/decision-maker.spec.js.snap
components/decision-maker.jsx
components/decision-maker.spec.js
components/index.jsx
demos/init-jsx.js
partials/decision-maker.html

This PR creates an **Decision Maker** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.

Add Decision Maker JSX component

---

components/__snapshots__/licence-confirmation.spec.js.snap
components/index.jsx
components/licence-confirmation.jsx
components/licence-confirmation.spec.js
demos/init-jsx.js
partials/licence-confirmation.html

This PR creates an **Licence Confirmation** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.

Add Licence Confirmation JSX component

---

components/__snapshots__/registration-confirmation.spec.js.snap
components/index.jsx
components/registration-confirmation.jsx
components/registration-confirmation.spec.js
demos/init-jsx.js
partials/registration-confirmation.html

This PR creates an **Registration Confirmation** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.

Add Registration Confirmation JSX component

---

components/__snapshots__/trial-banner.spec.js.snap
components/index.jsx
components/trial-banner.jsx
components/trial-banner.spec.js
demos/init-jsx.js
partials/trial-banner.html

This PR creates an **Trial Banner** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.

Add Trial Banner JSX component

---

components/__snapshots__/responsibility.spec.js.snap
components/index.jsx
components/responsibility.jsx
components/responsibility.spec.js
demos/init-jsx.js
partials/responsibility.html

This PR creates a **Responsibility** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.

Add Responsibility JSX component

---

components/__snapshots__/company-name.spec.js.snap
components/company-name.jsx
components/company-name.spec.js
components/index.jsx
demos/init-jsx.js
partials/company-name.html

This PR creates a **Company Name** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.

Add Company Name JSX component

---

components/__snapshots__/confirmation.spec.js.snap
components/confirmation.jsx
components/confirmation.spec.js
components/index.jsx
demos/init-jsx.js
partials/confirmation.html

This PR creates a **Confirmation Terms** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.

Add Confirmation JSX component

---

components/__snapshots__/state.spec.js.snap
components/index.jsx
components/state.jsx
components/state.spec.js
demos/init-jsx.js
partials/state.html

This PR creates an **(U.S.A.) State** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.

Add (U.S.A.) State JSX component

---

components/__snapshots__/section.spec.js.snap
components/index.jsx
components/section.jsx
components/section.spec.js
demos/init-jsx.js

Message inline partial has been changed to `children` which changes the API slightly.

Add the section JSX component

---

components/accept-terms.jsx
components/company-name.jsx
components/continue-reading.jsx
components/customer-care.jsx
components/decision-maker.jsx
components/delivery-address.jsx
components/delivery-city.jsx
components/delivery-county.jsx
components/delivery-postcode.jsx
components/delivery-start-date.jsx
components/form.jsx
components/licence-confirmation.jsx
components/licence-header.jsx
components/province.jsx
components/registration-confirmation.jsx
components/responsibility.jsx
components/state.jsx
components/submit.jsx
components/trial-banner.jsx

Also fixing whitespace that was breaking linting

Fix PropTypes to be propTypes

---

components/__snapshots__/delivery-option.spec.js.snap
components/delivery-option.jsx
components/delivery-option.spec.js
components/index.jsx
demos/init-jsx.js
partials/delivery-option.html

This PR creates a **Delivery Option** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.

Add Delivery Option JSX component

---

components/__snapshots__/progress-indicator.spec.js.snap
components/index.jsx
components/progress-indicator.jsx
components/progress-indicator.spec.js
demos/init-jsx.js

This PR creates a **Progress Indicator** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.

Add Progress Indicator JSX component

---

components/__snapshots__/payment-type.spec.js.snap
components/index.jsx
components/payment-type.jsx
components/payment-type.spec.js
demos/init-jsx.js
partials/payment-type.html

Convert the current PaymentType partial to a JSX component.

Add payment type JSX component

---

components/__snapshots__/payment-term.spec.js.snap
components/index.jsx
components/payment-term.jsx
components/payment-term.spec.js
partials/payment-term.html

Whitespace and character change needed in the partial.

Add Payment Term JSX Component

---

components/__snapshots__/loader.spec.js.snap
components/index.jsx
components/loader.jsx
components/loader.spec.js
demos/init-jsx.js

Add loader JSX component

---

components/__snapshots__/error-page.spec.js.snap
components/error-page.jsx
components/error-page.spec.js
components/index.jsx
demos/init-jsx.js

Add Error Page JSX Component

---

components/accept-terms.jsx
components/billing-postcode.jsx
components/delivery-postcode.jsx
components/first-name.jsx
components/industry.jsx
components/job-title.jsx
components/last-name.jsx
components/message.jsx
components/password.jsx
components/payment-term.jsx
components/payment-type.jsx
components/position.jsx
components/responsibility.jsx

I've spotted more proptypes issues  while integrating with next profile
none

fix proptype 🐿 v2.12.5

---

components/__snapshots__/debug.spec.js.snap
components/debug.jsx
components/debug.spec.js
components/index.jsx
demos/init-jsx.js

Use strings to avoid JSX sanitising the JS, Styles and HTML so this
component matches the partial. Once all applications use JSX this
should be rethought.

Add debug JSX component

---

components/__snapshots__/country.spec.js.snap
components/country.jsx
components/country.spec.js
components/index.jsx
demos/init-jsx.js
helpers/ncf-countries.js
test/helpers/ncf-countries.spec.js
utils/countries.js

Refactored how the handlebars helper orders countries into a utility
so the same functionality can be used for the component.
https://trello.com/c/WYujLFFR/1597-n-conversion-forms-new-major

Add Country JSX component

---

components/__snapshots__/billing-country.spec.js.snap
components/billing-country.jsx
components/billing-country.spec.js
components/index.jsx
demos/init-jsx.js

Based on the Country field this component
https://trello.com/c/WYujLFFR/1597-n-conversion-forms-new-major

Add Billing Country JSX Component

---

bower.json
main.scss
styles/continue-reading.scss
styles/customer-care.scss

🐿 v2.12.3
Migrates o-icons from v5 to v6

Migrates o-icons from v5 to v6

---

bower.json
main.scss
styles/banner.scss
styles/continue-reading.scss
styles/loader.scss
styles/package-change.scss
styles/payment-term.scss
styles/payment-type.scss

Migrates oTypography from v5 to v6

Migrates oTypography from v5 to v6 

---

bower.json

🐿 v2.12.5
No changes to the existing code appear to be needed.

Bumps o-loader to v4

---

bower.json
main.scss

🐿 v2.12.5
I had a discussion with Anthony on this, we believe more of a discussion is needed by the team but in the meantime, we kept this as simple as possible so that we are not held up in migrating our apps and libraries. 
Issue: https://github.com/Financial-Times/n-conversion-forms/issues/352

Migrates o-buttons from v5 to v6

---

styles/continue-reading.scss
styles/message.scss

Fixes some build errors in sass as a result of the update to `o-color` and `o-typography`.

Origami Upgrade: o-color and o-typography fixes in Sass

---

main.scss

Fixes a colour contrast error reported by Pa11y.

fix: specify button type for debug buttons.

---

components/__snapshots__/fieldset.spec.js.snap
components/fieldset.jsx
main.scss
partials/fieldset.html

🐿 v2.12.5
Removes form classes and adds ncf__legend.

Changes fieldset.html

---

components/__snapshots__/payment-term.spec.js.snap
components/payment-term.jsx
partials/payment-term.html
styles/_shared.scss
styles/payment-type.scss

Some styling updates for things missed as part of the origami migration
|   ![Screenshot 2020-01-02 at 11 34 48](https://user-images.githubusercontent.com/35035/71665349-73b58480-2d54-11ea-981e-62807f1e90aa.png)     |    ![Screenshot 2020-01-02 at 11 34 53](https://user-images.githubusercontent.com/35035/71665353-79ab6580-2d54-11ea-9b3c-602855d7733f.png)   |
| ![Screenshot 2020-01-02 at 11 13 15](https://user-images.githubusercontent.com/35035/71665359-80d27380-2d54-11ea-80a1-7720afa561cc.png) | ![Screenshot 2020-01-02 at 11 30 33](https://user-images.githubusercontent.com/35035/71665363-862fbe00-2d54-11ea-80d1-430af5d499c5.png) |

Payment page fixes

---

bower.json

Bumps o-messages which should fixes some specificity problems.

Bump o-message for specificity problems 

---

styles/payment-term.scss

| <img width="619" alt="1579102042" src="https://user-images.githubusercontent.com/708296/72446598-c3ac3680-37ab-11ea-8b53-4b423bd98e51.png"> | <img width="623" alt="1579101984" src="https://user-images.githubusercontent.com/708296/72446615-cdce3500-37ab-11ea-9c3e-a4a7ac28ad31.png"> |

Fix: payment terms radio button positioning

---

components/__snapshots__/delivery-postcode.spec.js.snap

For some reason when I did a rebase and merge my branch did not pull in all the changes in master and this caused one set of tests to fail. This fixes that. 🐿 v2.12.5

Fixes master build failure

---

main.scss

Tiny design change requested.
[Ticket](https://financialtimes.atlassian.net/jira/software/projects/AC/boards/971?selectedIssue=AC-50)
|<img width="393" alt="1580124457" src="https://user-images.githubusercontent.com/708296/73171966-db63b300-40f9-11ea-838b-e29ef5ecb770.png">|<img width="416" alt="1580125048" src="https://user-images.githubusercontent.com/708296/73171981-e1f22a80-40f9-11ea-88f8-1591f7c0d3cd.png">|

Tweak spacing on list description items 🐿 v2.12.5

---

components/__snapshots__/education-job-title.spec.js.snap
components/__snapshots__/email.spec.js.snap
components/__snapshots__/phone.spec.js.snap
components/education-job-title.jsx
components/education-job-title.spec.js
components/email.jsx
components/email.spec.js
components/index.jsx
components/phone.jsx
components/phone.spec.js
partials/education-job-title.html
partials/email.html
partials/phone.html

Adds a new job title field for educational licences and amends the email and phone number fields so that they're more suitable for educational licences
[Ticket](https://financialtimes.atlassian.net/jira/software/projects/USG/boards/969?selectedIssue=USG-15)

Amends for education licences

---

bower.json

use o-form 8.1.9 🐿 v2.12.5

---

components/company-name.spec.js
components/first-name.spec.js
components/industry.spec.js
components/job-title.spec.js
components/last-name.spec.js
components/password.spec.js
components/position.spec.js
components/province.spec.js
components/responsibility.spec.js
components/state.spec.js
jest.config.js
test-jest/helpers/setup.js

Adds a test setup file and removes duplicate code.

Adds a setup file 🐿 v2.12.5

---

components/delivery-option.jsx
components/delivery-start-date.jsx
components/fieldset.jsx
components/submit.jsx

Fix prop types

---

components/delivery-address.jsx
components/delivery-city.jsx
components/delivery-county.jsx

Adds max length to delivery address lines, county and city/town.
[Ticket](https://financialtimes.atlassian.net/jira/software/projects/AC/boards/971)

Adds max length

---

components/delivery-security-instructions.jsx
components/delivery-security-instructions.spec.jsx
components/index.jsx

This adds the delivery instructions component.
[Ticket](https://financialtimes.atlassian.net/jira/software/projects/AC/boards/971?selectedIssue=AC-77)

Delivery security instructions

---

components/__snapshots__/delivery-address.spec.js.snap
components/__snapshots__/delivery-city.spec.js.snap
components/__snapshots__/delivery-county.spec.js.snap
components/delivery-address.jsx
components/delivery-city.jsx
components/delivery-county.jsx
partials/delivery-address.html
partials/delivery-city.html
partials/delivery-county.html

🐿 v2.12.5
I have used a hardcoded value as this is the max value that membership expects.
[Ticket](https://financialtimes.atlassian.net/browse/MEM-3554)
Need to check if instructions and security instructions should be limited to 200 as they are in MMA

Adds maxlength to delivery address fields

---

Makefile
components/__snapshots__/accept-terms.spec.js.snap
components/accept-terms.jsx
main.scss
partials/accept-terms.html
test/partials/accept-terms.spec.js

- Add heading elements for terms and conditions.
- Add unordered list elements for individual terms and conditions.
- Add shorter label for checkbox.
[ticket](https://financialtimes.atlassian.net/browse/AC-112?atlOrigin=eyJpIjoiYjJiMzNjYzBmZTQ5NGFmNzkxNWQ3NDEwMDQ5ZDdiYWMiLCJwIjoiaiJ9)
| -- | -- |
| <img width="710" alt="image" src="https://user-images.githubusercontent.com/7748470/74549042-d6e72900-4f46-11ea-901a-388508cf43ee.png"> | <img width="710" alt="image" src="https://user-images.githubusercontent.com/7748470/74549372-6e4c7c00-4f47-11ea-8844-9255f2ce18c4.png"> |

Improve terms and conditions accessibility

---

components/__snapshots__/accept-terms.spec.js.snap
components/accept-terms.jsx
partials/accept-terms.html

Add missing attributes to fix E2E tests in `next-subscribe`

Add missing `for` attributes 🐿 v2.12.5

---

components/__snapshots__/accept-terms.spec.js.snap
components/accept-terms.jsx
partials/accept-terms.html

[Ticket](https://financialtimes.atlassian.net/browse/AC-187)

Customer Service -> Customer Care

---

components/fieldset.jsx
components/form.jsx

Noticed this was wrong/broken while working on `next-subscribe`.

Fix children proptypes for fieldset and form 🐿 v2.12.5

---

components/__snapshots__/delivery-option.spec.js.snap
components/delivery-option.jsx
partials/delivery-option.html

Text changes to the description that accompanies the "Paper vouchers" option in light of Covid-19
https://financialtimes.atlassian.net/browse/ACQ-181

ACQ-181 update text in case of PaperVoucher fulfilment

---

components/fieldset.jsx

Make descriptor a node so that it can include links or spans.
Required for: https://financialtimes.atlassian.net/browse/ACQ-206

Make descriptor a node so that it can include links/markup 🐿 v2.13.0

---

components/__snapshots__/delivery-option.spec.js.snap
components/delivery-option.jsx
partials/delivery-option.html

[Ticket](https://financialtimes.atlassian.net/browse/ACQ-221)

ACQ-221: Remove 'Stay safe!' from delivery options

---

components/__snapshots__/delivery-instructions.spec.js.snap
components/delivery-instructions.jsx
partials/delivery-instructions.html
styles/forms-additional-field-information.scss

This PR updates the Prompt for Delivery Instructions Component
| Before |
| ------ |
| After |
| ----- |

ACC-377 Update delivery instructions prompt

---

components/__snapshots__/payment-term.spec.js.snap
components/payment-term.jsx
partials/payment-term.html
test/partials/payment-term.spec.js

Wrongfully wrote `Digital Premium` instead of `Premium Digital` - this is a fix for it

ACQ-485 Invalid wording fix

---

components/__snapshots__/b2c-partnership-confirmation.spec.js.snap
components/b2c-partnership-confirmation.jsx

One word change to the wapo component.

change wording for wapo subscription

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
package.json
utils/zuora.js

A bit of housekeeping:
- update description
- fix typo
- remove refs to hbs partials
none

remove references to handlebars and partials 🐿 v2.13.0

---

components/__snapshots__/job-title.spec.js.snap
components/__snapshots__/organisation.spec.js.snap
components/email.jsx
components/index.jsx
components/job-title.jsx
components/last-name.jsx
components/organisation.jsx
components/organisation.spec.js

Add 'organisation' component.
Fix a few minor issues on existing components.
https://financialtimes.atlassian.net/browse/ACQ-524
When integrated in next subscribe, it looks like this:

ACQ-524: Organisation field

---

components/__snapshots__/graduation-date.spec.js.snap
components/graduation-date.jsx
components/graduation-date.spec.js
components/graduation-date.stories.js
components/index.jsx
components/licence-header.jsx
components/licence-sign-in.jsx
main.scss
package.json
styles/graduation-date.scss

Adds a component for capturing the graduation date of students joining educational licences.
https://financialtimes.atlassian.net/browse/UG-243

Graduation date component

---

components/__snapshots__/graduation-date.spec.js.snap
components/graduation-date.jsx
components/graduation-date.spec.js

Display error message below graduation date field
https://financialtimes.atlassian.net/browse/UG-243

Display error message below graduation date field

---

components/__snapshots__/education-job-title.spec.js.snap
components/education-job-title.spec.js

This test was absent from #471 .

Add a test for the isUSContract prop

---

components/__snapshots__/graduation-date.spec.js.snap
components/graduation-date.jsx
components/graduation-date.spec.js

Reword graduation date field label and add compliance text. 
https://financialtimes.atlassian.net/browse/UG-260
|     
|    
|

UG-260 Reword graduation date

---

components/lite-sub-confirmation.jsx

Adds US support number
https://financialtimes.atlassian.net/browse/UG-336
|     
|    <img width="595" alt="Screenshot 2020-12-09 at 15 12 47" src="https://user-images.githubusercontent.com/13418091/101648358-a4f10700-3a31-11eb-89fc-0703e2a62c24.png">
|

UG-339 — Add US support number

---

components/__snapshots__/licence-confirmation.spec.js.snap
components/b2c-partnership-confirmation.jsx
components/b2c-partnership-confirmation.stories.js
components/licence-confirmation.jsx

As above. It's Friday and I cba to offer more context.
Actually I will. In case anyone doesn't provide a CTA element, provide a default.

Provide default CTA element

---

test/utils/payment-term.spec.js
utils/payment-term.js

We forgot to update the 'data-base-amount' on updateOptions.
https://financialtimes.atlassian.net/browse/ACQ-776

update base amount on updateOptions

---

components/licence-sign-in.stories.js
components/licence-title.stories.js
components/organisation.stories.js

I spotted when looking at storybook that a few components were missing so I've added them.

Add storybook files for organisation, licence-sign-in and licence-title

---

components/__snapshots__/company-name.spec.js.snap
components/company-name.jsx
components/company-name.spec.js
components/company-name.stories.js

Make Company Name component optional or required by parameter.
https://financialtimes.atlassian.net/browse/ACQ-751

ACQ-751: Company Name component now support to be optional.

---

components/__snapshots__/billing-city.spec.js.snap
components/billing-city.jsx
components/billing-city.spec.js

add the property isHidden to the billing-city component since it was already used by next-subscribe but never implemented.
https://financialtimes.atlassian.net/browse/ACQ-752

ACQ-752: add the property isHidden to the billing-city component

---

components/lite-sub-confirmation.jsx
components/lite-sub-confirmation.stories.js

Update LiteSubscription with offerPrice prop
https://financialtimes.atlassian.net/browse/UG-414
|    <img width="864" alt="Screenshot 2021-03-19 at 17 45 57" src="https://user-images.githubusercontent.com/13418091/111821805-fc2d3000-88da-11eb-8d2d-46f7c7dac22f.png">    |    
|
- [x ] **Stories** updated to use this change
- [x ] **Accessibility** checked for screen readers and contrast
- [x ] **Design Review** ran past the designer
- [x ] **Product Review** ran past the product owner

Update LiteSubscription with offerPrice prop

---

components/__snapshots__/delivery-postcode.spec.js.snap
components/delivery-postcode.jsx
components/delivery-postcode.spec.js

Fixing label for other countries than USA/CAN
https://financialtimes.atlassian.net/browse/ACQ-937

ACQ-937: Fixing label for other countries than USA/CAN

---

styles/google-sign-in.scss

Fixing some cosmetic details on Google Sign In Button to align with Google designs.
| n-conversion-forms | next-subscribe |
| ![image](https://user-images.githubusercontent.com/13876273/117319749-e3c5a480-ae8b-11eb-8bd7-6c2157746016.png) | ![Screenshot 2021-05-06 at 16 53 27](https://user-images.githubusercontent.com/13876273/117319833-f6d87480-ae8b-11eb-88ca-28a084d07a85.png) |

Fixing some cosmetic details on Google Sign In Button

---

components/__snapshots__/billing-city.spec.js.snap
components/billing-city.jsx

Update billingCity component since it was showing the title when the method show from util was called
https://financialtimes.atlassian.net/browse/ACQ-979
|![image](https://user-images.githubusercontent.com/48696369/119676510-491a0f00-be14-11eb-8c4a-877badf816bb.png)|       ![image](https://user-images.githubusercontent.com/48696369/119676846-91d1c800-be14-11eb-94b0-84c58a07e8e4.png)|

ACQ-979: update billingCity component since it was not hidding properly

---

test/utils/delivery-start-date.spec.js
utils/delivery-start-date.js

Send csrf token with headers for delivery date check.
Must be released with this PR [next-subscribe](https://github.com/Financial-Times/next-subscribe/tree/ACQ-531_CSRF-for-delivery-date-check) 
[ACQ-531](https://financialtimes.atlassian.net/browse/ACQ-531)

ACQ-531 Implement CSRF protection for delivery date check.

---

.circleci/config.yml

Change CircleCI config to approve renovate or nori PRs before build. More information in the ticket description
https://financialtimes.atlassian.net/browse/ACQ-981

ACQ-981. Change CircleCI to approve renovate or nori PRs before build

---

components/__snapshots__/delivery-start-date.spec.js.snap
components/delivery-start-date.jsx
components/delivery-start-date.spec.js
package-lock.json

Following [some back and forth](https://financialtimes.slack.com/archives/C3LRB6JCE/p1624631834386200), Nevena decided that we should remove this paragraph altogether. 
https://financialtimes.atlassian.net/browse/ACC-1126

ACC-1126 Removed the nota bene paragraph altogether

---

CONTRIBUTING.md

Follow up from our slack discussion with @AniaMakes here: https://financialtimes.slack.com/archives/CSVRXFV6F/p1624632586294400
When you make a release, could you please link the PR(s) that the work was done in, as well as the actual Jira ticket link. Migration guide would be appreciated.
none

document release process

---

components/payment-term.jsx
components/payment-term.spec.js

Updates fixed term subscription payment term sub copy.
https://financialtimes.atlassian.net/browse/UG-541
|   <img width="1550" alt="Screenshot 2021-07-27 at 07 33 15" src="https://user-images.githubusercontent.com/13418091/127106900-09acdfe9-70eb-4751-91cd-054924c56fdb.png">     |    ![Screenshot 2021-07-30 at 17 27 03](https://user-images.githubusercontent.com/13418091/127683136-55b14b0c-9c93-4292-b998-aacc894d595c.png)   |

#UG-541 Update lite subscription payment term sub-copy

---

components/__snapshots__/personal-title.spec.js.snap
components/index.jsx
components/personal-title.jsx
components/personal-title.spec.js
components/personal-title.stories.js

Added PersonalTitle droppdown for conversion form
https://financialtimes.atlassian.net/browse/HIVE-126

HIVE-175: Added PersonalTitle

---

components/__snapshots__/delivery-address.spec.js.snap
components/delivery-address.jsx

Mainly what I say in the title.
[](https://financialtimes.atlassian.net/browse/ACQ-1293)
|![image](https://user-images.githubusercontent.com/48696369/142202507-9765502d-b068-4e62-b7d0-ee879f53ee40.png)|![image](https://user-images.githubusercontent.com/48696369/142202371-d52fb55d-d116-45ea-8198-a83fdad60e9e.png)|

ACQ-1293: fix typo delivery-address component

---

.github/workflows/gh-pages-deploy.yml

Trial & error: trying to explicitly install npm 7 just before running npm install.
[ACQ-1330](https://financialtimes.atlassian.net/browse/ACQ-1330)

ACQ-1330 github pages deployment test

---

components/__snapshots__/delivery-address.spec.js.snap
components/__snapshots__/graduation-date.spec.js.snap
components/delivery-address.jsx

Just a single update of labels according to the new figma design
[LINK](https://financialtimes.atlassian.net/browse/ACC-1252)

acc 1252 Adding small message address for us can

---

.eslintrc.js
components/message.jsx

fix a proptype that was causing a warning in next-subscribe unit tests
https://financialtimes.atlassian.net/browse/ACQ-1524

ACQ-1524: fix warning on next-subscribe unit tests

---

components/__snapshots__/payment-type.spec.js.snap
components/payment-type.jsx

Make checkbox selected by default
[JIRA](https://financialtimes.atlassian.net/jira/software/c/projects/ACC/boards/1461?modal=detail&selectedIssue=ACC-1657)

ACC1657 Fix "Use these details to pay faster next time" checkbox

---

components/__snapshots__/b2c-partnership-confirmation.spec.js.snap
components/b2c-partnership-confirmation.jsx
components/payment-term.jsx

- B2c copy changes
- Showing it for annual plans only
https://financialtimes.atlassian.net/browse/ACQ-1634

ACQ 1634 B2C Partnership copy changes

---

components/accept-terms.jsx
components/accept-terms.stories.js

Changes on component to hide the "accept terms" when is not needed.
https://financialtimes.atlassian.net/browse/ACQ-1666

ACQ-1666: small change on accept terms

---

components/__snapshots__/confirmation.spec.js.snap
components/confirmation.jsx

Show standard confirmation copy when not b2c
https://financialtimes.atlassian.net/browse/ACQ-1547

ACQ-1547 b2c partnership copy

---

components/__snapshots__/licence-header.spec.js.snap
components/__snapshots__/licence-title.spec.js.snap
components/licence-title.jsx

Via an email chain they complained about the license title having the `Start your free trial` on the title. 
https://financialtimes.atlassian.net/browse/ACQ-1747
| Before | After with displayName | After without displayName|
| ------ | ----- |----- |
|![Screenshot 2022-07-01 at 10 24 27](https://user-images.githubusercontent.com/1725956/176857510-dee4673b-398b-4a45-b43d-632e0a492a48.png)|![Screenshot 2022-07-01 at 10 27 03](https://user-images.githubusercontent.com/1725956/176857568-5128adce-2979-4674-ac62-4f0af4cf93d5.png)|![Screenshot 2022-07-01 at 10 25 05](https://user-images.githubusercontent.com/1725956/176857741-e47b99ca-20f7-4817-a013-a8a0d706601c.png)|

Simplify license title

---

helpers/index.js

we didn´t have a postcode reference for apac or emea regions, and we need the identify shipping helper for be used in next profile
[TICKET](https://financialtimes.atlassian.net/browse/ACC-1808)

ACC-1803: export identify shipping helper

---

components/__snapshots__/b2c-partnership-confirmation.spec.js.snap
components/b2c-partnership-confirmation.jsx

Make the description for b2c confirmation more generic.
https://financialtimes.atlassian.net/browse/ACQ-1767

Remove period from b2c confirmation

---

components/__snapshots__/licence-confirmation.spec.js.snap
components/licence-confirmation.jsx

Changing the copy as per ticket [ELE 220](https://financialtimes.atlassian.net/browse/ELE-220?atlOrigin=eyJpIjoiYWZmMTY2YzgzMTNjNGVmZGJjMWViZGYxOGU2NWJlZTYiLCJwIjoiaiJ9) on the licence-confirmation page
Snapshot for this change has also been updated

ELE 220 change joiner copy on confirmation page

---

components/accept-terms.jsx

Remove code related to newDigitalBuyFlowConsent  flag
https://financialtimes.atlassian.net/browse/ACQ-1658

ACQ 1658 - Remove code related to newDigitalBuyFlowConsent  flag

---

components/delivery-instructions.jsx

Description
Updating delivery instructions field placeholder for CEMEA region countries
Ticket
https://financialtimes.atlassian.net/browse/ACQ-1661
https://financialtimes.atlassian.net/browse/ACQ-1826

ACQ 1661-1826: Placeholder delivery instructions for CEMEA

---

components/__snapshots__/phone.spec.js.snap
components/phone.jsx

Changes phone label according to https://www.figma.com/file/cM1GFLBd1wste0gE31x2n8/New-Buy-Flow?node-id=3518%3A47737
https://financialtimes.atlassian.net/browse/ACQ-1807

Update phone field description

---

components/__snapshots__/debug.spec.js.snap
components/debug.jsx

This to help with email verification flow on next-subscribe.
https://financialtimes.atlassian.net/browse/ACQ-1899

ACQ-1899: add verificationEmail to debug helper

---

.circleci/config.yml
package-lock.json
package.json

Upgrade nodejs version to 16.x
[Ticket](https://financialtimes.atlassian.net/browse/ACQ-1882)

ACC-1878: upgrade to node 16

---

components/__snapshots__/company-name.spec.js.snap
components/company-name.jsx

for some countries we want to restrict the company name to be maximum of 40 characters.so adding a max length attribute to the company name 
https://financialtimes.atlassian.net/browse/ACC-1990
- [y] **Documentation** updated or created
- [ y] **Tests** written for new or updated for existing functionality
- [ y] **Stories** updated to use this change
- [ y] **Product Review** ran past the product owner

ACC-1990 maxlength attribute on company limit

---

utils/delivery-option-messages.js
utils/delivery-option-messages.spec.js

Update copy for delivery option messages for CEMEA 
https://financialtimes.atlassian.net/browse/ACQ-1961
Docs: https://docs.google.com/spreadsheets/d/1S_tqNIRadrbi3dgJx7ZFm-EWPkeW8XVYWc_bB23RSwg/edit#gid=1656024258
- [√ ] **Tests** written for new or updated for existing functionality

ACQ-1961: CEMEA delivery option copy messages

---

components/__snapshots__/delivery-option.spec.js.snap
components/__snapshots__/delivery-po-box.spec.js.snap
components/delivery-po-box.jsx
utils/delivery-option-messages.js
utils/delivery-option-messages.spec.js

Copy change
https://financialtimes.atlassian.net/browse/ACQ-2009

Update delivery time for US and CAD from 3 to 5 business days

---

styles/message.scss

The scope of this ticket is to address the following outstanding issues with error messages on forms:
[ACQ-2013](https://financialtimes.atlassian.net/browse/ACQ-2013)

ACQ-2013: fix message styles

---

package-lock.json

From following PRs:
https://github.com/Financial-Times/n-conversion-forms/pull/706
https://github.com/Financial-Times/n-conversion-forms/pull/702
https://github.com/Financial-Times/n-conversion-forms/pull/721
https://github.com/Financial-Times/n-conversion-forms/pull/691
https://github.com/Financial-Times/n-conversion-forms/pull/701

Devops: Add @dependabot dependencies requests

---

components/__snapshots__/payment-term.spec.js.snap
components/payment-term.jsx
utils/payment-term.js
utils/payment-term.spec.js

https://financialtimes.atlassian.net/browse/ACQ-2191

ACQ-2191: add country to payment term

---

utils/payment-term.js

We get an incorrect symbol on the payment term because we compute some price client side and forgot to pass in the symbol.
It turns out that we already compute the prices server side, no need to do this in the client.
related PR: https://github.com/Financial-Times/next-subscribe/pull/2537
https://financialtimes.atlassian.net/browse/ACQ-2186

fix incorrect currency symbol

---

.babelrc
.babelrc.js
README.md

- fix: add sourceType unambiguous to babelrc
- https://financialtimes.atlassian.net/browse/ACQ-1893
|![image](https://github.com/Financial-Times/n-conversion-forms/assets/22417566/fea59b3e-4fe1-4d38-9376-02d71a77b96d)|![image](https://github.com/Financial-Times/n-conversion-forms/assets/22417566/54f52d27-d138-4235-a5e1-8465fb944d17)|

ACQ-1893: fix broken imports by fixing babel config

---

package-lock.json
package.json

dotcom component updated to 4.0.3
](https://financialtimes.atlassian.net/browse/ACQ-2419)

ACQ-2419: n-conversion-forms release problem due to toolkit migration

---

components/__snapshots__/graduation-date.spec.js.snap

This PR is a repeat of https://github.com/Financial-Times/n-conversion-forms/pull/708/files by @jenniferemshepherd and which we can probably consider a traditional part of our new year festivities 😁 
N/A
N/A

Update snapshot to correct available dates

---

.eslintignore
.eslintrc.js
.prettierignore
.toolkitrc.yml
components/accept-terms-subscription.jsx
components/confirmation.jsx
package-lock.json
package.json

- chore: fix and update prettier and esLint configs
- https://financialtimes.atlassian.net/browse/ACQ-2540

ACQ-2540: fix prettier, eslint and lint-staged configs

---

package-lock.json
package.json

Removing node version 16
https://financialtimes.atlassian.net/browse/ACQ-2662

Removing node version 16

---

components/__snapshots__/delivery-start-date.spec.js.snap
components/delivery-start-date.jsx

Update default print delivery text
https://financialtimes.atlassian.net/browse/ACQ-2783

ACQ-2783: Update default print delivery text

---

components/__snapshots__/delivery-start-date.spec.js.snap
components/delivery-start-date.jsx
package.json

change "The first print edition you will receive is on" to "The first print edition you will receive is"
https://financialtimes.atlassian.net/browse/ACQ-2798

ACQ-2798: Change print date copy

---

components/__snapshots__/delivery-start-date.spec.js.snap
components/delivery-start-date.jsx

This PR rolls back changes regarding `startMessage`.
[ACQ-2891](https://financialtimes.atlassian.net/browse/ACQ-2891)
[ACQ-2891]: https://financialtimes.atlassian.net/browse/ACQ-2891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACQ-2891: added class to update text when date changes

---

components/delivery-option.jsx
utils/delivery-option-messages.js
utils/delivery-option-messages.spec.js

Updated param names and structure on `DeliveryOption` component to make code more readable and understandable.
[ACQ-2901](https://financialtimes.atlassian.net/browse/ACQ-2901)
[ACQ-2901]: https://financialtimes.atlassian.net/browse/ACQ-2901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACQ-2901: param names and structure refactoring
