Financial-Times/n-conversion-forms

main.scss

This wrongly indents fields against titles, raised with origami so should hopefully be fixed in future versions.
🐿 v2.9.0

Overridding o-forms padding

---

main.scss
partials/accept-terms.html
partials/fieldset.html
partials/submit.html
tests/partials/accept-terms.spec.js
tests/partials/fieldset.spec.js
tests/partials/submit.spec.js

- Adding back button to submit
- Add corp signup terms and conditions
- Ability to visually hide the label
🐿 v2.9.0

Adding corp signup differences

---

partials/accept-terms.html
tests/partials/accept-terms.spec.js

🐿 v2.9.0
As part of rolling out longer terms to the rest of the world we need to refresh the terms across the board. This includes reducing the current terms and adding these new terms to only a test sample of people. This PR also removes the knowledge of offers from the terms selector, this is to reduce the reliance on other data structures.
https://trello.com/c/5EPnjhfb/526-change-the-longer-terms-copy-to-show-to-usa-a-b-rest-of-world

Renaming usa to extended terms

---

partials/password.html

🐿 v2.9.0
The rules for passwords in the FT are as the copy specifies, this requires a change in `next-signup` that will be done in conjunction with this.
https://trello.com/c/Zh0QEVJO/500-updating-security-rules-around-our-passwords

Changing password rules copy

---

bower.json
demos/data.json
main.scss
partials/message.html
tests/partials/message.spec.js

Adds a `o-message` message template and styles to `ncf` for `next-profile` originally but will be used across all forms.
https://trello.com/c/StvBSqtX/509-next-profile-page-shows-error-message-without-styling

Adding message template and styles

---

main.scss
partials/social-login.html
tests/partials/social-login.spec.js

Adds a social button template with only one Google style which is all we support currently
https://trello.com/c/WZItLvDy/540-details-form-page-google-sign-in

Google login button

---

demos/app.js
demos/data.json
partials/email.html
tests/helpers.js
tests/partials/email.spec.js

Adds the ability to have a confirm email address in the email moustache template. Adds `showConfirm` and `hasConfirmError` parameters to allow this.
Also changed the demo to display the implementation code in a textarea for easier distinction from the main component and ease of copy paste.
https://trello.com/c/BZMtdexU/609-add-confirm-email-address-to-n-conversion-forms

Confirm email address for emails

---

partials/package-change.html
tests/partials/package-change.spec.js

🐿 v2.10.0
Removing the price from the package change component as this is no longer part of the design
Doing as part of this - https://trello.com/c/MMzEyGiM

remove weekly price from package-change

---

demos/data.json
main.scss
partials/email.html
partials/form.html
partials/postcode.html
tests/partials/post-code.spec.js

🐿 v2.10.3
Adds postcode field and adds styling for the form wrapper.
https://trello.com/c/vyUcLmgO/536-details-form-page-filling-in-the-fields

Add postcode partial and add styling for form wrapper

---

demos/data.json
helpers/ncf-countries.js
package.json
partials/country.html
partials/delivery-country.html
tests/helpers/ncf-countries.spec.js

When a filterList is not defined - split the countries and arrange the top used first.
🐿 v2.10.3

Allow splitting countries by usage

---

partials/country.html
partials/delivery-country.html

As there is an extra level of nesting for the optgroup work, the value lookup needs to be updated to reflect that.
🐿 v2.10.3

Correct scope for value

---

partials/accept-terms.html
tests/partials/accept-terms.spec.js

Since the extended terms have been rolled out this flag is no longer needed.
https://trello.com/c/riRjYe91/682-showextendedterms-clean-up

Remove isExtended flag

---

README.md
package.json
tests/utils/email.spec.js
tests/utils/validation.spec.js
utils/email.js
utils/validation.js

Also added a utilities section to the readme with more details for how to use each of the JS utils.
I left the `event-notifier` and `tracking` as TBD as they can be better described by someone who knows more about them/understands them better.

Port across validation & email utilities from next-subscribe.

---

main.scss
partials/apple-pay.html
styles/payment.scss
tests/partials/apple-pay.spec.js
tests/utils/payment.spec.js
utils/payment.js

The PR you've all been waiting for, the first stab at Apple Pay using the Payment Request API.
Example usage -
Include the Handlebars template
```
{{> n-conversion-forms/partials/apple-pay isHidden=true }}
```
Initalise the Javascript
```javascript
const product = {value: 1.00, currency: 'GBP', label: 'Standard FT'};
const payment = new Payment(window, Payment.METHOD_APPLE_PAY, product);
const shown = await payment.showPaymentButton();
if (!shown) {
// Browser doesn't support the payment method
}
```
https://trello.com/c/lBW3ZJwU/653-apple-pay-as-new-payment-method

Payment utility implementing Apple Pay using Payment Request API

---

tests/utils/validation.spec.js
utils/validation.js

🐿 v2.10.3
Validates the form when initialised so that forms that are pre-filled on page load can have the submit button re-enabled.
https://trello.com/c/4enpx6cF/743-next-subscribe-fix-button-on-all-pages

Add validation on init

---

partials/accept-terms.html

Remove the mailto and link them out to the contact us page
https://trello.com/c/hIUKTV6G/747-buy-flow-tcs-sentence-update-for-people-to-chat-or-call-cs-as-opposed-to-email-them

Stop people emailing customer services

---

bower.json
main.scss
partials/progress-indicator.html
tests/partials/progress-indicator.spec.js

As trailblazers we created a component that was then implemented by Origami. This PR removes our original work so that we can replace it with the component.
https://trello.com/c/wUinlgf5/834-use-o-stepped-progress-instead-of-our-home-brew-progress-styles
| --- | --- |
| <img width="525" alt="screenshot 2019-01-31 at 15 48 51" src="https://user-images.githubusercontent.com/1721150/52066083-bf254880-256f-11e9-9d4c-29e0db9dcd77.png"> | <img width="511" alt="screenshot 2019-01-31 at 16 39 53" src="https://user-images.githubusercontent.com/1721150/52069579-e29fc180-2576-11e9-87de-00cfa40c0e31.png"> |

Using origami component for progress

---

bower.json

There is an unrecoverable mismatch in o-message versions so for the time being we will roll this back.

Rolling back o-message

---

partials/payment-type.html
tests/partials/payment-type.spec.js

Only show the required payment methods when rendering the page. By default none show, which I'm not sure is the right call but thought it may be safer.

Enable and disable payment types from showing

---

main.scss

Fixes a content size issue when using fieldsests. Also fixes offset radio button problem.
| Before  | After  |
|---------|--------|
|![beforeFieldset]|![afterFieldset]|
|![beforeRadio]|![afterRadio]|
[beforeFieldset]: https://user-images.githubusercontent.com/708296/52403088-d4ddc500-2abd-11e9-956c-408b889a003b.png
[afterFieldset]: https://user-images.githubusercontent.com/708296/52403095-d7d8b580-2abd-11e9-809c-2924c0c196c8.png
[beforeRadio]: https://user-images.githubusercontent.com/708296/52403509-ccd25500-2abe-11e9-891f-4041edc03b54.png
[afterRadio]: https://user-images.githubusercontent.com/708296/52403512-cfcd4580-2abe-11e9-9239-542ff3f52bab.png

Fix content size for fieldset

---

tests/utils/payment-type.spec.js
utils/payment-type.js

Just ran into this error on `next-subscribe`.

Only remove payment type if already present.

---

README.md
tests/utils/payment-term.spec.js
utils/payment-term.js
utils/payment-type.js

When a user changes their billing address the Payment Terms will update. The `updateOptions` will build the new options from existing ones an eventually remove the old ones.
Fixed a but that meant the first input with a checked attribute was being classed as the input's value rather than the actual selected input.

Update payment term options

---

partials/country.html

Used to target the country field in `next-signup` so this has to be `billingCountry`.

Change ui item name if isBillingCountry

---

partials/package-change.html
tests/partials/package-change.spec.js

Now pages are accessed just via GET requests there is no longer a
need for this to be a form

Remove package change form

---

partials/payment-type.html
tests/utils/payment-type.spec.js
utils/payment-type.js

When a payment type is not recognised we should error and display an
error to the user. Message has been added to the template and the
utility will help with displaying it client side

Add error message and util helper for payment type

---

tests/utils/payment-type.spec.js
utils/payment-type.js

If the shown payment term was copied from the current selected
term then it would mark the new one as checked when shown.

Fix payment term show bug which checked by default

---

partials/payment-type.html
styles/payment.scss

🐿 v2.12.1
Pulling across the logos used on the current signup form.

Add logos for paypal and direct debit

---

bower.json
partials/payment-type.html
styles/payment.scss
tests/utils/direct-debit-guarantee.spec.js
tests/utils/form-element.spec.js
utils/direct-debit-guarantee.js
utils/form-element.js

🐿 v2.12.1
Add DD Guarantee copy below payment type selector.
https://trello.com/c/ggg5CVC9/939-3-direct-debit-guarantee

Add DD Guarantee

---

main.scss
partials/confirmation.html
tests/partials/confirmation.spec.js

🐿 v2.12.0
Updated confirmation page styling. 
Added different data displaying capabilities if some of the data is missing {email / confirmation_details}
https://trello.com/c/RBa9tkWU/819-8-buy-flow-confirmation-page
With full details:
when confirmation data is missing:

Updated confirmation page style

---

partials/confirmation.html
tests/partials/confirmation.spec.js

Added DD mandate link
🐿 v2.12.3
Currently there is a button, which will be visible if ddMandateLink is generated.
This PR does not include the styles yet. Will have to wait for Lucinda to come back from holidays to design this link
https://trello.com/c/qb963YhC/880-3-buy-flow-add-direct-debit-mandate-to-confirmation-page

Added DD mandate link

---

main.scss
partials/message.html
styles/message.scss
tests/partials/message.spec.js

Error messages on a white background did not look nice, this is because the red being used was based on them showing on the paper background color.
https://trello.com/c/xVc7RwxM/843-5-buy-flow-error-message-review
| --- | --- |
| <img width="473" alt="Screenshot 2019-04-15 at 15 13 55" src="https://user-images.githubusercontent.com/1721150/56139591-1c3a7300-5f91-11e9-9063-fda20fd1e5c9.png"> | <img width="475" alt="Screenshot 2019-04-15 at 15 12 54" src="https://user-images.githubusercontent.com/1721150/56139551-0d53c080-5f91-11e9-8c2e-b03ed397dd80.png"> |

White background styles for messages

---

partials/message.html
tests/partials/message.spec.js

These new features will be used in subscribe to allow us to pin point messages within client side code showing and hiding them as appropriate.
https://trello.com/c/xVc7RwxM/843-5-buy-flow-error-message-review

Add hidden and name parameters to message partial

---

partials/payment-type.html
styles/payment-type.scss

🐿 v2.12.3
Discovered this visual bug while testing DD on next subscribe.
|Before|After|
|-|-|
|<img width="562" alt="1555584323" src="https://user-images.githubusercontent.com/708296/56356049-b7209080-61cf-11e9-9693-96258d4c73a2.png">|<img width="610" alt="1555584262" src="https://user-images.githubusercontent.com/708296/56356034-b1c34600-61cf-11e9-8535-a6aacb0ed3b9.png">|

Fix Zuora overlay styling

---

main.scss
partials/confirmation.html

We were not using origami styles as they should be used. This PR fixes our usage by minimising component duplication in final css. I was able to reduce oTypographySans and oTypographySerif usage
https://trello.com/c/G1HP59O2/1097-5-update-mainscss-to-not-output-double-styling

1097 5 update mainscss to not output double styling

---

demos/app.js
demos/data.json
demos/main.scss

`Fields` is an inline partials that is expected by fieldset and form and that make them fail in the demo.
Is not anyway a field we should had to our partials so I preferred to register it just to make the demo not to brake and confuse engineers that are using the repo for the first time.
Fixed a typo

Allow for partials to be defined in demo data.

---

styles/payment-type.scss

🐿 v2.12.3
Horizontal payment option layout was limiting possible option number.
vertical layout will fix it
https://trello.com/c/yw4iOnrr/1138-3-payment-method-options-layout-is-wrong

Updated payment method option layout from horizontal to vertical

---

Makefile
README.md
bower.json
demos/app.js
demos/data.json
demos/main.js
demos/main.scss
main.scss
partials/loader.html
styles/loader.scss
tests/helpers.js
tests/partials/loader.spec.js
tests/utils/loader.spec.js
utils/loader.js

🐿 v2.12.3
Loader component for use in all of our forms. Includes JS util for controlling it.
Note: I've had to do a fair bit of hacking around in the demos/test code to make it so that I could use `@partial-block` because I felt that defining named inline partials wasn't as neat. At least now we have the ability to do so going forward 😄
https://trello.com/c/0xuGAx9L/1074-5-loaders-on-all-the-pages
Note: the example where data is passed in is incorrect here (`title=title`). I've fixed it since making the gif.

Add Loader component

---

tests/utils/validation.spec.js
utils/validation.js

After talking to Origami it seems disabling the submit button is not a great user experience. This stops the disabling of the submit button and exposes the validateForm method from oForms so that next-subscribe can do it's magic...
https://trello.com/c/tUrGMboj/1128-1-payment-page-apple-pay-become-a-subscriber-cta-never-enabled

Remove disabled submit button

---

README.md
partials/loader.html
tests/utils/zuora.spec.js
utils/zuora.js

🐿 v2.12.3
Also sneaking in a cheeky loader fix 😬
The hostedPaymentPageCallback wasn't working and I found out about the `runAfterRender` function. I figure it's a more useful event to be binding to anyway.

Add renderCallback to zuora util

---

README.md
tests/utils/loader.spec.js
utils/loader.js

🐿 v2.12.3
https://trello.com/c/0xuGAx9L/1074-5-loaders-on-all-the-pages

Enable passing in content for the loader when calling the show method

---

utils/zuora.js

Seems babel in next-subscribe does not fix the prototypes like typescript/node does, this is needed to fix them so we can do `instanceof` tests.
https://trello.com/c/ZH273Wxn/1092-5-analytics-add-event-which-fires-when-we-show-the-user-a-message

Make sure Zuora errors get the correct prototype

---

demos/data.json
main.scss
partials/fieldset.html

Design review changes to adjust the margins of the fieldset header and descriptor
https://trello.com/c/tRS4iLrq/1108-1-gap-between-details-first-field-too-large
https://trello.com/c/NwZgjVfg/1110-1-gap-between-payment-title-and-field-too-large-missing-blurb
| --- | --- |
| <img width="418" alt="Screenshot 2019-04-29 at 18 08 46" src="https://user-images.githubusercontent.com/1721150/56913567-e5448100-6aa9-11e9-98cb-df8e40534297.png"> | <img width="391" alt="Screenshot 2019-04-29 at 18 08 18" src="https://user-images.githubusercontent.com/1721150/56913572-e8d80800-6aa9-11e9-8d6f-3d3204513fa5.png"> |
| <img width="416" alt="Screenshot 2019-04-29 at 18 09 00" src="https://user-images.githubusercontent.com/1721150/56913582-ef667f80-6aa9-11e9-95fb-3ce2707221dc.png"> | <img …

Adjust the margins in the fieldset

---

README.md

Add Snyk Badge to readme.
This is a proposal nothing related to the current Backlog.
*Why I think we should do that (when we have time as tech debts)?*
Because it immediately communicates to developers that are reading the README that we use Snyk and the repo is tracked and (hopefully) in a good state by the security perspective.
Additionally, it just take 2 minutes to open a PR.
This is how the readme will look like for this repo

doc: add Snyk badge on README

---

tests/utils/validation.spec.js
utils/validation.js

🐿 v2.12.3
Checkboxes were only updating on blur which led to some odd behaviour (see before gif below)
https://trello.com/c/aiopoOpg/1129-1-tc-strange-behaviour
|Before|After|
|-|-|
|![ft-checkbox-validation-before](https://user-images.githubusercontent.com/708296/57020164-66258900-6c20-11e9-8090-08d03d7e18f8.gif)|![ft-checkbox-validation-after](https://user-images.githubusercontent.com/708296/57020175-6c1b6a00-6c20-11e9-835e-50f826587f80.gif)|

Make checkboxes validate on click

---

partials/payment-term.html
styles/payment-term.scss

🐿 v2.12.3
default price type weight was bold. in ft we use semibolds. I have updated label--title class to use semibold
I have also created new class for ncf-payment-type__price which will be used in next-subscribe to display annual price in semibold as well
https://trello.com/c/3g3HvElM/1114-1-cost-needs-to-be-bold

Updated payment type weights to semi bold

---

partials/payment-term.html

🐿 v2.12.3
Adds a paragraph break in the copy underneath the payment options.
https://trello.com/c/c0giULyF/1131-1-add-paragraph-break-in-large-amount-of-text
|Before|After|
|-|-|
|<img src="https://user-images.githubusercontent.com/708296/57023656-82c6be80-6c2a-11e9-9175-01761b59dfab.png">|<img src="https://user-images.githubusercontent.com/708296/57023671-8a866300-6c2a-11e9-9326-f88ec5b1d9b7.png">|

Update payment options copy

---

partials/payment-type.html
styles/payment-type.scss

Previously, the icons were remaining the same colour and were therefore barely visible.
This is a twofer: https://trello.com/c/Und1hTOS/1115-1-paypal-button and https://trello.com/c/OoF1bLJP/1116-1-direct-debit-button

Show light versions of paypal/direct debit icons when selected.

---

styles/payment-term.scss

Made the padding match the spacing of the form fields for consistency.
https://trello.com/c/7I9Rwnhx/1106-1-awkward-looking-radio-button
|Before|After|
|-|-|
|<img src="https://user-images.githubusercontent.com/708296/57298030-184dcc80-70c9-11e9-9307-ad3f96e5c48f.png">|<img src="https://user-images.githubusercontent.com/708296/57298044-20a60780-70c9-11e9-9087-1c636b178012.png">|

Fix spacing above payment term description

---

main.scss
partials/package-change.html

Adjust how the change package button is vertically aligned
https://trello.com/c/Q3Sw71Ul/1146-1-make-change-button-more-vertically-centered
| --- | --- |
| <img width="536" alt="Screenshot 2019-05-07 at 12 54 42" src="https://user-images.githubusercontent.com/1721150/57297592-dec89180-70c7-11e9-812f-e31435715829.png"> | <img width="536" alt="Screenshot 2019-05-07 at 12 54 26" src="https://user-images.githubusercontent.com/1721150/57297597-e425dc00-70c7-11e9-8489-0abc894d8871.png"> |

Adjust the vertical align of the change package button

---

main.scss
partials/progress-indicator.html

This is to line our progress indicator up correctly to margins
| Small | Large |
| --- | --- |
| <img width="473" alt="Screenshot 2019-05-07 at 15 03 32" src="https://user-images.githubusercontent.com/1721150/57305947-ceb9ad80-70d9-11e9-9142-415102783ace.png"> | <img width="562" alt="Screenshot 2019-05-07 at 15 03 16" src="https://user-images.githubusercontent.com/1721150/57305951-d2e5cb00-70d9-11e9-8d7e-1c7a9c664f4b.png"> |

Adjust margins on the progress indicator

---

bower.json
main.scss

50px margin on a small screen is not good
| --- | --- |
| ![screencapture-ft-buy-offer-683995bf-ed3f-2fd6-d589-1628ebad1629-registered-2019-05-07-14_31_20](https://user-images.githubusercontent.com/1721150/57303274-e0e51d00-70d4-11e9-9b0b-7dcc6ea8a75c.png) | ![screencapture-local-ft-5050-buy-offer-683995bf-ed3f-2fd6-d589-1628ebad1629-registered-2019-05-07-14_30_49](https://user-images.githubusercontent.com/1721150/57303279-e3477700-70d4-11e9-8ce3-b23c360577bb.png) |

Reduce the wrappers margins on small screens

---

README.md
partials/loader.html
tests/partials/loader.spec.js

🐿 v2.12.3
Provides the option to set the variable `showLoader` in the HTML in order to show loader without javascript.

Show loader

---

demos/app.js

This is because some objects like arrays are not liked by mustache
when they are serialised.

Use template variables instead of serialised objects

---

tests/utils/zuora.spec.js
utils/zuora.js

🐿 v2.12.3
This is so we can show/hide the iframe if there's a problem fetching the config.
https://trello.com/c/tDfDnNrM/1119-1-large-gap-between-error-and-payment-method

Add zuora iframe to zuora util

---

docs/PARTIALS.md
partials/fieldset.html
tests/partials/fieldset.spec.js

I need to be able to pass in the heading text for a `fieldset` containing accessibility related markup.
While I was there I noticed that the partials documentation was sorely lacking so I refactored what was there and added the documentation for the `fieldset` and `loader` partials. The rest will need to be added later as there are still 25+ missing partials from this file.
For clarity, this is what the implementation would look like:
```handlebars
{{#> n-conversion-forms/partials/fieldset name="details" headingLevel="h1" }}
{{#*inline "header"}}
<span class="o-normalise-visually-hidden">Personal </span>Details<span class="o-normalise-visually-hidden"> (page 1 of 3)</span>
{{/inline}}
{{/ n-conversion-forms/partials/fieldset }}
``` …

Fieldset accessibility improvements

---

partials/password.html
tests/helpers.js
tests/partials/password.spec.js

Saw some error messages in our logs where the Joi validation was firing and our client side wasn't. This will allow us to set patterns to better align our validation with Joi and eventually Membership.

Add pattern to password for custom validation

---

tests/utils/tracking.spec.js
utils/tracking.js

Analytics has asked us to remove empty values from tracking data as it makes their extraction tables messy.
https://trello.com/c/Oyrn3QMM/1203-1-analytics-remove-empty-values

Remove empty values from tracking data

---

README.md
partials/loader.html
tests/partials/loader.spec.js
tests/utils/loader.spec.js
utils/loader.js

🐿 v2.12.3
When the loader pops up, screen readers will immediately read the loader message and also prevent tabbing in the background. After the loader is done, any element that had focus previously gets its focus restored.
https://trello.com/c/ut124coM/1171-accessibility-payment-payment-method-loading-overlay-text-underneath-overlay-is-readable-by-voiceover-confusing

Add a11y capability to the Loader

---

partials/phone.html

🐿 v2.12.3
The minimum and maximum validity attributes were set wrong. This led to a customer entering too short a phone number. The form submitted OK and the user was informed that they had been successful.
Meanwhile, a POST to the _Marketo_ platform happened in the background, and failed, even though the success page had already appeared. So the customer thought they were successful but marketing couldn't find their details in Marketo.
https://trello.com/c/zIrJT8AH/864-lead-creation-bug
Before:
After:

Fix min/max length attributes

---

.github/PULL_REQUEST_TEMPLATE.md

🐿 v2.12.3
As discussed in the last Retro session... this should help us (mostly me 😅) remember to run stuff past Design/UX.
https://trello.com/c/V0Skk59N/175-add-checkbox-to-pr-template-for-design-review

Add question about Design/UX to PR template

---

tests/utils/email.spec.js
utils/email.js

I've got a hunch that some browsers are triggering CORs and therefore will need this option set to be able to get the cookies.
https://trello.com/c/VphFoylC/1224-receiving-lots-of-token-mismatch-errors

Include credentials in the email exists call

---

README.md
package.json
tests/helpers/dom.js
tests/utils/loader.spec.js
tests/utils/validation.spec.js
utils/validation.js

🐿 v2.12.3
This is needed for cases like the one in `next-subscribe` (see gif below) where some offerIds aren't available in all countries.
~~I'm getting this up here for review before writing documentation and tests as it feels quite messy to me and could do with optimisation (I've been staring at this problem too long).~~
https://trello.com/c/YIg1eEwm/1194-5-behaviour-when-user-selects-a-country-subscription-is-not-available-in

Add custom validation capability

---

demos/data.json
docs/PARTIALS.md
main.scss
partials/licence-confirmation.html
tests/partials/licence-confirmation.spec.js

This is the confirmation page for licence subscriptions
https://trello.com/c/21YM5ELJ/1252-1-b2b-trial-confirmation-page
| Full | Trial |
| --- | --- |
| <img width="537" alt="Screenshot 2019-06-03 at 12 52 41" src="https://user-images.githubusercontent.com/1721150/58799975-a05abf80-85fe-11e9-97f9-37565dc0dd94.png"> | <img width="489" alt="Screenshot 2019-06-03 at 12 56 51" src="https://user-images.githubusercontent.com/1721150/58800195-2119bb80-85ff-11e9-8c88-fc4fba02c974.png"> |

Add the confirmation page for licence subscriptions

---

demos/data.json
docs/PARTIALS.md
main.scss
partials/continue-reading.html
styles/continue-reading.scss
tests/partials/continue-reading.spec.js

Display the content article the user was reading including a link if they can read it.
https://trello.com/c/ADGmnXnY/1268-1-content-message-on-b2b-trial-form

Add the continue reading component

---

README.md
docs/PARTIALS.md
main.scss
partials/app-banner.html
styles/app-banner.scss
tests/partials/app-banner.spec.js
tests/utils/app-banner.spec.js
utils/app-banner.js

Banner and utility are part of the corp signup b2b work. These can easily be ported across to work in the next-subscribe work.
https://trello.com/c/GIAR14DQ/1253-5-add-bottom-app-banner-to-confirmation-page

Add the app banner partial and utility

---

demos/data.json
partials/payment-term.html
styles/payment-term.scss
tests/partials/payment-term.spec.js

Allows us to display discounted offers
https://trello.com/c/vGowLNS4/1214-5-sale-price-shown-on-payment-page

Add the discount label for payment terms

---

README.md
main.scss
partials/trial-banner.html
styles/app-banner.scss
styles/banner.scss
tests/partials/trial-banner.spec.js

🐿 v2.12.3
Added banner with new design for next-corp-signup
https://trello.com/c/WF2pSe2e/1240-1-add-top-banner-for-b2b-trial-forms
Narrow view:
Wide view:

Added trial banner to be used in next-corp-signup

---

styles/payment-term.scss

After implementation it was needed to be tweaked a little.
https://trello.com/c/vGowLNS4/1214-5-sale-price-shown-on-payment-page

Tweak font size and padding on discount label

---

partials/payment-term.html
tests/partials/payment-term.spec.js

Moves all the static copy about payment terms into the template and out of next-subscribe. This makes this module more portable but also removes some templating work out of next-subscribe.
This also implements the feature in the card where we show extra copy for the annual term if not discounted.
Implemented with https://github.com/Financial-Times/next-subscribe/pull/412
https://trello.com/c/TSVDTwjG/1205-3-add-save-25-terms-copy-when-not-a-sale-offer

Move all payment term copy into partial

---

partials/payment-term.html
tests/utils/payment-term.spec.js
utils/payment-term.js

Now the copy is not set in the response use the existing terms and just update the price.
https://trello.com/c/TSVDTwjG/1205-3-add-save-25-terms-copy-when-not-a-sale-offer

Fix updateOptions method of payment terms util

---

demos/data.json
docs/PARTIALS.md
main.scss
partials/package-change.html
styles/package-change.scss
tests/partials/package-change.spec.js

Displays payment terms including prices in the package-change component.
https://trello.com/c/M5xVHmPw/1231-5show-cost-on-the-stepped-buy-flow
| Desktop | Mobile |
| --- | --- |
| <img width="670" alt="Screenshot 2019-06-10 at 15 39 20" src="https://user-images.githubusercontent.com/1721150/59203213-0793e900-8b96-11e9-8f59-69c90193c574.png"> | <img width="412" alt="Screenshot 2019-06-10 at 15 39 39" src="https://user-images.githubusercontent.com/1721150/59203218-08c51600-8b96-11e9-85cc-c53480ebc192.png"> |

Add payment term display to the package-change component

---

partials/company-name.html
partials/email.html
partials/firstname.html
partials/lastname.html
partials/password.html
partials/phone.html
partials/postcode.html

Added "autocomplete" attributes to all input fields in the signup form, based on the [input purposes spec](https://www.w3.org/TR/WCAG21/#input-purposes).
https://trello.com/c/z11SBdhZ/1280-dacautocompleteissue1
I have trouble running `next-signup` locally at the moment. I'd be great if someone could do a sanity check on it.

Add autocomplete to firstname

---

partials/debug.html

🐿 v2.12.3
Realised this was messing up the `csrfToken` in `next-subscribe`.

Don't fill hidden input fields with helper

---

demos/data.json
demos/main.scss
partials/package-change.html
styles/package-change.scss
tests/partials/package-change.spec.js

The price component which shows the different pricing options across the form pages is too large and is distracting users from the form. There is an updated to reduce the size of this visually.
https://trello.com/c/QOr2zuzp/1312-update-the-offer-price-component-in-next-subscribe
Before: 
After:

Price offer update

---

partials/debug.html

We were ending up with two cookies if you used the environment switcher

Add wildcard for subdomains onto flag cookie

---

README.md
tests/utils/salesforce.spec.js
utils/salesforce.js

For Marketo we need to convert ISO country codes to Salesforce country names. Adding this utility here as it may be useful elsewhere and reduces the need to depend on `n-common-static-data` for our applications.
https://trello.com/c/DGsVQQ0U/1291-8-add-marketo-api-request-to-next-subscribe

Add salesforce utility to convert country codes

---

demos/app.js
demos/data.json
docs/PARTIALS.md
main.scss
partials/city-town.html
partials/county.html
partials/delivery-address.html
partials/delivery-instructions.html
partials/delivery-start-date.html
tests/partials/city-town.spec.js
tests/partials/county.spec.js
tests/partials/delivery-address.spec.js
tests/partials/delivery-instructions.spec.js
tests/partials/delivery-start-date.spec.js

🐿 v2.12.4
This adds various partials we need for print delivery forms with the exception of the fulfilment options (coming up next).
Also fixed the broken demo examples again (not showing the values of the parameters properly). Not sure where my previous fix for that went ¯\\\_(ツ)\_/¯
https://trello.com/c/N460ES43/1018-3-delivery-page-render-page-with-address-section
<details><summary>City/town</summary>
</details>
<details><summary>County</summary>
</details>
<details><summary>Delivery address</summary>
</details>
<details><summary>Delivery instructions</summary>
</details>
<details><summary>Delivery start date</summary>
</details>

Add print delivery related fields

---

demos/data.json
docs/PARTIALS.md
partials/licence-header.html
tests/partials/licence-header.spec.js

This is used across trial and company licence forms, centralising in n-conversion-forms

Add licence-header partial

---

demos/data.json
docs/PARTIALS.md
partials/confirmation.html
tests/partials/confirmation.spec.js

for users who have bought a print only product (not for Bundle) we should remove the"Start Exploring" button and have something else : ie "Thank you"or a link to direct them to the Epaper
https://trello.com/c/sPiPtd8t/736-1-delivery-journey-different-cta-on-the-confirmation-page

Print confirmation

---

demos/data.json
docs/PARTIALS.md
main.scss
partials/debug.html
partials/delivery-option.html
styles/_shared.scss
styles/payment-term.scss
tests/partials/delivery-option.spec.js

🐿 v2.12.4
Also fixed up the `payment-terms` in the demo.
https://trello.com/c/Za8rkwXw/1321-5-delivery-page-fulfilment-options

Add delivery-options partial

---

partials/delivery-option.html

🐿 v2.12.4
Just realised I had named this in a plural fashion but it should actually be singular.

Make delivery option input name singular

---

package.json
partials/billing-country.html
tests/utils/validation.spec.js

When selecting the "Please select a country" option, the change handler was being executed with a blank countryCode, leading to issues when attempting to retrieve the gateway details. This disables the default option so its unavailable for selection.
https://trello.com/c/keOttSIW/1363-payment-page-config-call-is-throwing-errors

fix: disable default empty country option

---

partials/billing-postcode.html
partials/debug.html
partials/delivery-postcode.html
tests/partials/billing-postcode.spec.js
tests/partials/delivery-postcode.spec.js
utils/billing-postcode.js

- use consistent `postcode` naming for postal codes
- keep postcode.html template unchanged for backward compatibility (it has a mixture of postcode/postCode), it is marked as deprecated
n/a
n/a

Postcode lowercase

---

demos/data.json
docs/PARTIALS.md
partials/delivery-address.html
tests/partials/delivery-address.spec.js

🐿 v2.12.3
use separate deliveryAddress lines rather than array
https://trello.com/c/dxgP3IRA/1328-5-submit-delivery-step
n/a

use separate deliveryAddress lines rather than array

---

partials/delivery-start-date.html

🐿 v2.12.4
When updating the start date, this needs to be selectable in the JS so it can be updated when the response from membership comes back.
https://trello.com/c/m1k5q0pA/1320-8-delivery-page-delivery-start-date

Add js class to start date text

---

partials/delivery-instructions.html

🐿 v2.12.3
Richard Quinto mentioned that we should add more information to help avoid customer service issues down the line.
https://trello.com/c/x19PJx5l/1379-1-add-extra-delivery-instructions-copy

add note to delivery instructions

---

README.md
tests/utils/delivery-option.spec.js
tests/utils/delivery-start-date.spec.js
tests/utils/validation.spec.js
utils/delivery-option.js
utils/delivery-start-date.js
utils/validation.js

🐿 v2.12.4
Adds delivery option and delivery start date utils as well as fixing up the custom validation stuff to work with async/await and allow markup in error messages.
https://trello.com/c/m1k5q0pA/1320-8-delivery-page-delivery-start-date

Add delivery option and start date utils

---

partials/delivery-instructions.html

🐿 v2.12.3
Richard Quinto mentioned that we should add more information to help avoid customer service issues down the line.
Copy to be added is below:
"Any instructions which will help us deliver your newspaper, i.e. door colour, letterbox location, as well as information on how you want us to deliver it i.e. post through the letter box, place in plastic bag etc"
https://trello.com/c/x19PJx5l/1379-1-add-extra-delivery-instructions-copy

change delivery option copy

---

docs/PARTIALS.md
partials/confirmation.html
tests/partials/confirmation.spec.js

🐿 v2.12.4
The floodlight tracking was thrown off because trial subscriptions that were shown this confirmation template were being lumped together with the normal ones. See tracking code here: https://github.com/Financial-Times/n-ui/blob/master/components/n-ui/tracking/third-party/floodlight.js#L9-L14
https://trello.com/c/4hH7LRlP/1448-bau-bug-pixels

Add data-signup-is-trial attribute for floodlight pixel tracking

---

main.scss

🐿 v2.12.4
This was making the a11y tests fail here: https://circleci.com/gh/Financial-Times/next-subscribe/8455

Fix a11y contrast ratio issue

---

partials/payment-type.html
styles/payment-type.scss

🐿 v2.12.4
Annoyingly, this thing doesn't show up on local.ft.com and _still takes up the space_. Don't really want to pollute the partial with an `isDev` flag so just leaving it as is ¯\\\_(ツ)\_/¯
[Ticket](https://trello.com/c/CCOKa66K/1447-add-security-seal-to-single-page-and-newspaper)

Add GlobalSign badge to payment type partial

---

styles/payment-type.scss

🐿 v2.12.4
Because this wasn't working locally, I didn't see that the image was wrapped in an unstyled link with a bottom border.
[Ticket](https://trello.com/c/CCOKa66K/1447-add-security-seal-to-single-page-and-newspaper)
|Before|After|
|-|-|
|<img width="413" alt="1566223019" src="https://user-images.githubusercontent.com/708296/63271263-ad985980-c291-11e9-93f8-d0b5bb0b5105.png">|<img width="413" alt="1566223030" src="https://user-images.githubusercontent.com/708296/63271278-b4bf6780-c291-11e9-8dbb-b7e84857aca2.png">|

Remove border from globalsign link

---

partials/payment-term.html
test/partials/payment-term.spec.js

Make the new forms more similar to the old to remove any chance of negatively impacting conversion.

Use weekly price instead of discount copy

---

styles/payment-term.scss

Updating the sale colour to be consistent with the barriers
| --- | --- |
| <img width="180" alt="Screenshot 2019-08-19 at 15 18 09" src="https://user-images.githubusercontent.com/1721150/63272915-dbcb6880-c294-11e9-8df6-e98b15243549.png"> | <img width="260" alt="Screenshot 2019-08-19 at 15 14 00" src="https://user-images.githubusercontent.com/1721150/63272926-dff78600-c294-11e9-95e0-f21d2599e510.png"> |

Update sale colour on payment-term from black to claret

---

styles/payment-type.scss

There was a slight misalignment caused by some standard o-forms label styles. Using a very specific style to override this which is not the greatest but hopefully can be removed after o-forms v7.
_Ignore the missing secure payment badge, it does not show on local_
| --- | --- |
| <img width="472" alt="Screenshot 2019-08-20 at 13 19 17" src="https://user-images.githubusercontent.com/1721150/63346595-3aecb400-c34d-11e9-9ee7-5bf58d77058d.png"> | <img width="482" alt="Screenshot 2019-08-20 at 13 19 45" src="https://user-images.githubusercontent.com/1721150/63346602-4049fe80-c34d-11e9-8b47-b84f662295dc.png"> |

Fix payment type misalignment issue

---

styles/loader.scss
styles/payment-type.scss
utils/loader.js

Currently we can only show a loader across a whole page, but with payment type changes we don't have to block the whole page. This allows you to show a loader by passing in an element to the show function.
| --- | --- |
| <img width="1232" alt="Screenshot 2019-08-20 at 15 19 17" src="https://user-images.githubusercontent.com/1721150/63355512-282eab00-c35e-11e9-8224-31c2e570430a.png"> | <img width="1233" alt="Screenshot 2019-08-20 at 15 21 10" src="https://user-images.githubusercontent.com/1721150/63355520-2bc23200-c35e-11e9-9c3b-42b31f94f93b.png"> |

Add loader methods to show loader on specific element

---

utils/loader.js

`next-subscribe` is failing Pa11y tests as there is a page loader in the template and an element loader when it's being tested. This means there are two things labelled by and described by the same id's which is bad. This changes the id's of the element loader so they do not conflict.
Spotted by @umbobabo

Change the label and description ids to not conflict with page loader

---

docs/PARTIALS.md
main.scss
partials/customer-care.html
styles/customer-care.scss
test/partials/customer-care.spec.js

Adds a "Contact Customer Support" partial.  🐿 v2.12.4
https://trello.com/c/ZoemhRqe/1472-1-build-inelible-page
Mobile:
Desktop:

feat: customer contact page

---

demos/data.json
docs/PARTIALS.md
main.scss
partials/customer-care.html
partials/error-page.html
test/partials/customer-care.spec.js
test/partials/error-page.spec.js

Due to the custom responsive behaviour on the customer-care page and the different ordering of content and the additional requirement to embed external markup in the error page component, I thought it prudent to make it a separate partial.
https://trello.com/c/wd9l2S8D/1439-1-build-failed-transaction-error-template
The livechat content is included via `@partial-block` functionality (embedded from next-retention)

feat: error page template

---

partials/payment-term.html
test/partials/payment-term.spec.js

Currently we are only showing 4 weeks for the trial duration. We can have trials of different durations so we need the ability to override this.
https://trello.com/c/sor7sqad/1159-3-month-trials-are-displaying-as-only-1-month

Add the ability to override the trial duration in payment term

---

partials/debug.html
partials/delivery-address.html
partials/delivery-city.html
test/partials/delivery-city.spec.js

When we send the delivery data to membership we send this as field as `city` rather than `cityTown`.
https://trello.com/c/npfV689n/1514-town-does-not-get-prepopulated-when-returning-to-the-delivery-step

Rename deliveryCityTown to deliveryCity

---

demos/data.json
partials/accept-terms.html
test/partials/accept-terms.spec.js

Adds transition specific terms into the accept-terms partial
🐿 v2.12.4
https://trello.com/c/YQYDZCon/1525-1-make-tcs-text-relevant-to-transitions
N/A

feat: add transition-terms

---

test/partials/accept-terms.spec.js

🐿 v2.12.4
Fixes typos is accept-terms unit tests after work to include the transition specific terms.
https://trello.com/c/YQYDZCon/1525-1-make-tcs-text-relevant-to-transitions
<summary>
End Of Term
<details>
</details>
</summary>
<summary>
Immediate
<details>
</details>
</summary>

fix: typos in test

---

test/utils/delivery-start-date.spec.js
utils/delivery-start-date.js

🐿 v2.12.4
This is needed to be able to disable/enable the start date field when the `EV` delivery option is selected in `next-subcribe`.
[Trello card](https://trello.com/c/pfhod8db/1532-electronic-vouchers-should-disable-start-date-field)

Add disable/enable to start date util

---

partials/payment-type.html

🐿 v2.12.4
The Global Sign SSL padlock image is not showing up correctly and makes the sign up form look broken sometimes. 
Removing until we can get a better solution from Global Sign.
[Ticket](https://trello.com/c/WIFoCaPC/1494-1-remove-the-global-sign-ssl-image-as-its-not-loading-correctly)

Disable globalsign security seal

---

partials/debug.html

🐿 v2.12.4
Handlebars can't access env variables 🤦‍♂ so using the `data-next-app` property that's present on the `html` element. Side benefit to this is that it will work locally too \o/

Use app name from html element for debug email

---

docs/PARTIALS.md
docs/UTILS.md/POSTCODE.md
partials/billing-postcode.html
partials/delivery-postcode.html
test/partials/billing-postcode.spec.js
test/partials/delivery-postcode.spec.js
test/utils/billing-postcode.spec.js
test/utils/delivery-postcode.spec.js
test/utils/postcode.spec.js
utils/billing-postcode.js
utils/delivery-postcode.js
utils/postcode.js

🐿 v2.12.3
This functionality allows for the retrieval of the correct terminology of postcode based on the country of the user.
USA -> zip code
Canada -> postal code
default -> postcode
This also updates any reference to postcode to the correct terminology when the user changes their country, i.e Canada to USA - postal code to zip code.
This work deals with both billing and delivery postcode.
https://trello.com/c/w3jLsixQ/1476-3-postcode-logic-for-us-and-canada-migration

Adds functionality to get and change postcode reference based on country

---

partials/package-change.html
styles/package-change.scss

The grid not being in next-subscribe meant that changes to the grid size had to be done in two repositories. Moving this to next-subscribe means that it has better control of the component.
[Ticket](https://trello.com/c/bHHabGTX/1521-gride-width-tcs)

Remove grid from package change into next-subscribe

---

partials/debug.html

Recently removed the domain in cookies that were being set in environments other than production for our e2e tests. As `/logout` will only clear cookies with the domain of `.ft.com` this meant our session cookies were not being cleared. Instead remove cookies with the name `FTSession` and `FTSession_s` where ever they are from.

Fix logout debug button by directly clearing cookie

---

components/__snapshots__/phone.spec.js.snap
components/phone.jsx
components/phone.spec.js
partials/phone.html

JSX version of the phone field.
As well as converting the partials params into props, I have made other values such as the fields `id` and `name` attributes into props so that these can be configured. I have defaulted these values to those used in the Handlebars partial.
[Ticket](https://trello.com/c/Jha4GGCA/77-jsx-poc-phone-number)

JSX POC: Phone field

---

partials/payment-term.html
test/partials/payment-term.spec.js

**Breaking Change** Trials can contain multiple payment terms which was not handled in our existing forms. Instead of having the payment term name being `trial` we now pass the actual name of the term along with a `isTrial` flag which will mark the option as a trial payment term.
[Ticket](https://trello.com/c/DGCm7Xw1/1560-print-trial-payment-terms-issues)

Update payment terms to display trial info for all payment options

---

components/__snapshots__/message.spec.jsx.snap
components/message.jsx
components/message.spec.jsx
package.json

This port the message component.
It looks me roughly 1.5 hours to port this component.
The average of the components seems to be simpler than this one. Few are more complex than this.
There are currently 47 partials to be ported minus 4 already ported, so 43.
Very likely we won't need all of them so let say 35.
35 x 1.5 hours is around 1 week and a half for 1 Engineer. I don't think it should take so long but let's discuss it together before we proceed further. 
In addition to the context, the following are the partials required just for the current /profile:
n-conversion-forms/partials/message [DONE]
n-conversion-forms/partials/email
n-conversion-forms/partials/firstname
n-conversion-forms/partials/lastname
n-conversion-forms/partials/phone [DONE]
n-conversion-forms/partials/fieldset …

feat: Port partial component

---

partials/debug.html

Reverts Financial-Times/n-conversion-forms#259
It turns out that if we don't use the `.ft.com` domain for our local development environment cookies we get cookie issues when transitioning between ft.com and local.ft.com. `next-subscribe` now lays cookies with the `.ft.com` domain so we can revert this change and `/logout` will successfully remove them for both local.ft.com and ft.com.

Revert "Fix logout debug button by directly clearing cookie"

---

bower.json
demos/main.scss
demos/views/index.html

o-techdocs is being decommissioned, use o-layout instead.
| --- | --- |
| <img width="900" alt="Screenshot 2019-10-24 at 15 53 29" src="https://user-images.githubusercontent.com/1721150/67497829-7457dd80-f676-11e9-8bb7-e2949b091804.png"> | <img width="936" alt="Screenshot 2019-10-24 at 15 52 07" src="https://user-images.githubusercontent.com/1721150/67497752-54281e80-f676-11e9-95e6-4f32a5e68c6e.png"> |

Remove o-techdocs for o-layout

---

.babelrc
.circleci/config.yml
.gitignore
Makefile
components/index.jsx
components/phone.jsx
demos/app-jsx.js
demos/app.js
demos/init-jsx.js
demos/views/jsx.js
demos/webpack.jsx.config.js
package.json
partials/debug.html

- jsx components compiled/transpiled
- some basic demo added for jsx components 
- https://trello.com/c/gqAxe7Em/79-add-some-sort-of-demo-to-n-conversion-forms-for-the-jsx-components
- https://trello.com/c/XO3wbGq3/78-jsx-tooling-build-for-n-conversion-forms-integrate-a-component-with-next-profile
make build => is run by circle ci to generate the transpiled code in /dist
make build-demo => builds demo, replaces former make build
jsx demos added to existing `make run` under route /jsx
I've also added a demo with minimal dependencies:
`node demos/app-jsx.js`
go to http://host:5005

compile jsx and add demo

---

helpers/ncf-countries.js

Currently there are 45 countries in the list which falls below the 50 minimum. This minimum is arbitrary and anything over 20 countries should be helped with the grouping.

Reduce the limit for grouping to improve the user experience

---

package.json

The [`classnames`](https://github.com/JedWatson/classnames) package should be in `dependencies` (rather than `devDependencies`) so that it is installed when installing `n-conversion-forms`.

fix: move classnames package into dependencies

---

demos/data.json
partials/payment-term.html

Also updated the demo data to display the terms more correctly.
[Ticket](https://trello.com/c/q1fBrWTP/1626-add-a-full-stop-after-payment-options-copy)

Add full stops at the end of trial payment term copy

---

main.scss
partials/delivery-instructions.html

[Ticket](https://trello.com/c/CvSCoXVx/1623-bit-too-much-lineheight)
| <img width="462" alt="Screenshot 2019-10-30 at 14 46 01" src="https://user-images.githubusercontent.com/1721150/67868595-1ae32900-fb24-11e9-903b-58e101f9aa19.png"> | <img width="481" alt="Screenshot 2019-10-30 at 14 42 26" src="https://user-images.githubusercontent.com/1721150/67868611-1f0f4680-fb24-11e9-939b-9925ffd411d2.png"> |

Reduce the lineheight around delivery instructions

---

partials/payment-term.html
test/utils/payment-term.spec.js
utils/payment-term.js

The price and trial price dynamically updated when the user changes their currency, make sure the weekly price is also updated.
[Ticket](https://trello.com/c/5xJLpZ6E/1633-currency-for-weekly-prices-doesnt-adapt-to-billing-country-on-new-buy-flow-forms)
| <img width="532" alt="Screenshot 2019-11-01 at 09 36 50" src="https://user-images.githubusercontent.com/1721150/68016013-77ad2380-fc8b-11e9-85a9-d752f256302d.png"> | <img width="546" alt="Screenshot 2019-11-01 at 09 36 30" src="https://user-images.githubusercontent.com/1721150/68016017-7b40aa80-fc8b-11e9-825a-4f0e14e24c4c.png"> |

Update the weekly price when updating payment terms

---

partials/confirmation.html
test/partials/confirmation.spec.js

Weekend only subscriptions don't have access to the site or the epaper so we deadend them.
[Ticket](https://trello.com/c/QqbHDTch/1636-remove-cta-on-weekend-only-print-from-confirmation-page)

Add option to hide CTA on B2C confirmation page

---

components/__snapshots__/industry.spec.js.snap
components/industry.jsx
partials/industry.html

As per: https://github.com/Financial-Times/n-conversion-forms/pull/295#discussion_r342049064.

Correct apostrophe in Industry partial/component error text

---

components/__snapshots__/app-banner.spec.js.snap
components/app-banner.jsx
components/app-banner.spec.js
components/index.jsx
demos/init-jsx.js
partials/app-banner.html

This PR creates an **App Banner** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.
React will escape ampersands in `href` values, and so the same needed to be applied to the HBS partial, which resulted in no change to the output HTML - e.g. `https://itunes.apple.com/app/apple-store/id1200842933?pt=246269&amp;ct=onsite-app-promotion&amp;mt=8` gets output as:
- [GitHub - facebook/react Issues: Escaped ampersands in query params within src/href attributes](https://github.com/facebook/react/issues/6873).

Add App Banner JSX component

---

components/__snapshots__/delivery-address.spec.js.snap
components/delivery-address.jsx
components/delivery-address.spec.js
components/index.jsx
demos/init-jsx.js
partials/delivery-address.html

This PR creates a **Delivery Address** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.

Add Delivery Address JSX component

---

components/__snapshots__/delivery-city.spec.js.snap
components/delivery-city.jsx
components/delivery-city.spec.js
components/index.jsx
demos/init-jsx.js
partials/delivery-city.html

This PR creates a **Delivery City** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.

Add Delivery City JSX component

---

components/__snapshots__/delivery-start-date.spec.js.snap
components/delivery-start-date.jsx
components/delivery-start-date.spec.js
components/index.jsx
demos/init-jsx.js
partials/delivery-start-date.html

This PR creates a **Delivery Start Date** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.

Add Delivery Start Date JSX component

---

components/__snapshots__/licence-header.spec.js.snap
components/index.jsx
components/licence-header.jsx
components/licence-header.spec.js
demos/init-jsx.js
partials/licence-header.html

This PR creates an **Licence Header** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.
I wonder if there is good reason for the usage of triple-stash (for the welcomeText), as it has forced me to use `dangerouslySetInnerHTML` which is best avoided where possible.
> Handlebars HTML-escapes values returned by a `{{expression}}`. If you don't want Handlebars to escape a value, use the "triple-stash", `{{{`
> `{{{foo}}}`
- [Handlebars.js](http://handlebarsjs.com/expressions.html).
- [ReactJS: DOM Elements - dangerouslySetInnerHTML](https://reactjs.org/docs/dom-element …

Add Licence Header JSX component

---

utils/form-element.js
utils/payment-term.js
utils/payment-type.js
utils/postcode.js

We've seen errors like this in sentry https://sentry.io/organizations/financial-times/issues/1183641809/?project=1420825&query=is%3Aunresolved+payment&statsPeriod=14d because some browsers don't have a `forEach` method on `NodeList`'s returned from `querySelectorAll`. 
Use `for` instead which is much more universal, not sure why this isn't being polyfiled.
Hunch that this may be related to the ticket below as client side errors may affect the ability to process the payment form.
[Ticket](https://trello.com/c/0D9f8C14/1651-subscriptions-being-sent-to-membership-without-payment-method-id)

Fix cross browser issue looping over NodeList

---

components/__snapshots__/province.spec.js.snap
components/index.jsx
components/province.jsx
components/province.spec.js
demos/init-jsx.js
partials/province.html

This PR creates an **(Canadian) Province** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.

Add (Canadian) Province JSX component 🐿 v2.12.5

---

docs/PARTIALS.md
partials/submit.html
test/partials/submit.spec.js

🐿 v2.12.5
Adds the ability to specify a custom text for the back button.
[Ticket](https://trello.com/c/QkchK4G1/1610-cancel-reasons-page-for-trials)

Allow the passing of custom back button text 

---

main.scss
partials/submit.html
test/partials/submit.spec.js

🐿 v2.12.5
The designs for the cancel journey need the buttons to be full width.
[Ticket](https://trello.com/c/QkchK4G1/1610-cancel-reasons-page-for-trials)

Allow submit buttons to be full width

---

components/__snapshots__/delivery-instructions.spec.js.snap
components/delivery-instructions.jsx
components/delivery-instructions.spec.js
components/index.jsx
demos/init-jsx.js
partials/delivery-instructions.html

This PR creates an **Delivery Instruction** JSX component that matches the behaviour and usage of the existing Handlebars (HBS) partial, with tests to ensure they match.

Add Delivery Instruction JSX component

---

components/index.jsx

Use export instead of importing and exporting later to reduce
duplication and reduce instances of merge conflicts.

Export all components from files

---

components/password.jsx
components/password.spec.js

The Personal Details page on Account Settings will need to have three password fields displayed, but with small differences between them.
- They will each have their own label.
- None of them will have placeholder text.
- One will have microcopy above the field that is different to the existing copy.
- Two will not have any microcopy.
- Only one will have the "Show password" checkbox next to it.
This PR adds the following props to the `<Password>` JSX component:
- `label` - Text that will be used for the label of the field. Defaults to "Password".
- `placeholder` - Text that will be used for the placeholder text on the field. Defaults to "Enter a password".
- `hasDescription` - Whether or not to show the description for the field. Defaults to `true`.
- `description` - The description text …

More options for the Password component

---

components/__snapshots__/customer-care.spec.js.snap
components/customer-care.jsx
components/customer-care.spec.js
docs/PARTIALS.md
partials/customer-care.html
styles/customer-care.scss
test/partials/customer-care.spec.js

🐿 v2.12.5
The Cancel Confirmation page needs to display this information but without the phone icon and with the spacing a lot more compact.
[Ticket](https://trello.com/c/hFrTJ1J2/1613-trial-cancellation-confirmation-page)
| <img width="645" alt="1574171020" src="https://user-images.githubusercontent.com/708296/69242673-41333c00-0b99-11ea-93c4-0aac1b703e7d.png">|<img width="625" alt="1574242215" src="https://user-images.githubusercontent.com/708296/69242697-4db79480-0b99-11ea-800b-abbbb2224407.png">|

Add compact version of customer care message

---

bower.json
demos/main.scss

Upgrades the devDependencies bower components.
We expect the build to fail on this one, as there are other dependencies that need upgrading. Once all our changes are merged into the `origami-major-upgrade` feature branch, we _should_ have a build that passes.

Origami Upgrade: Dev dependencies for the demo

---

bower.json
styles/package-change.scss

Removed use of `oGridGenerate` as that outputs all the `o-grid*` classes, none of which are used by the components here. If they are used by the apps that consume `n-conversion-forms` then those apps should include them themselves.
We expect the build to fail on this one, as there are other dependencies that need upgrading. Once all our changes are merged into the `origami-major-upgrade` feature branch, we should have a build that passes.

Upgrade version of o-grid

---

bower.json

🐿 v2.12.5
Does not appear to require any changes according to the [migration notes](https://github.com/Financial-Times/o-stepped-progress/blob/master/MIGRATION.md#migrating-from-v1-to-v2)

Bumps o-stepped-progress from v1 to v2

---

bower.json
components/__snapshots__/message.spec.jsx.snap
components/message.jsx
partials/message.html
test/partials/message.spec.js

Main change was that we now use a separate `n-message--inner` class for the "inner" layout.
We expect the build to fail on this one, as there are other dependencies that need upgrading. Once all our changes are merged into the `origami-major-upgrade` feature branch, we should have a build that passes.

Upgrade o-message to the latest major version

---

main.scss

We were using `oSpacingByName` with "s0" as the size, but that size doesn't exist, so we were getting Sass compilation errors.

fix: use 0 (zero) instead of mixin for spacing.

---

components/__snapshots__/delivery-instructions.spec.js.snap
components/delivery-instructions.jsx
components/delivery-instructions.spec.js
partials/delivery-instructions.html

JSX escapes all HTML attributes which causes issues for the
placeholder in the delivery instructions component. Because a line
break entity is used to put instructions across multiple lines this
breaks our tests as JSX will escape this. By adding the ability to
override the placeholder we can have two working but different default
placehodlers for JSX and Handlebars but still have tests pass.
https://trello.com/c/hcOuBGMF/1680-delivery-instructions-placeholder-look-wrong

Add placeholder override attribute

---

bower.json
components/__snapshots__/payment-type.spec.js.snap
components/payment-type.jsx
partials/payment-type.html
styles/payment-type.scss
test/utils/payment-type.spec.js
utils/payment-type.js

Uses the main `oExpander` mixin and classnames for styling and client-side JavaScript, instead of adding `o-expander` content into our own classnames. Includes changes to client-side code for initialising the expander, as we no longer need to pass in the classnames for the content and trigger elements.

Upgrade o-expander from v4 to v5

---

components/__snapshots__/delivery-option.spec.js.snap
components/delivery-option.jsx
demos/init-jsx.js
partials/delivery-option.html
styles/_shared.scss
test/partials/delivery-option.spec.js

I forgot to add the Delivery Option component into the `o-forms` migration PR (#353), so here is the component with the necessary mark-up and styling changes.
There's some stupidly long selectors to override some of the default `o-forms` styling. Not ideal, and with more time I would try to see if we can improve upon them.
I've also passed delivery options in as props to this component in the JSX demo, as there were none, and so the component does not get displayed in the demo.
~~**The base branch has been set to `origami-upgrade-forms` to make it easier to see the changes. If PR #353 has already been merged in by the time this PR is reviewed, please change the base branch to `origami-major-cascade` before merging.**~~

Origami Upgrade: o-forms migration for Delivery Option component

---

bower.json
components/__snapshots__/billing-postcode.spec.js.snap
components/__snapshots__/delivery-postcode.spec.js.snap
components/__snapshots__/loader.spec.js.snap
components/__snapshots__/payment-type.spec.js.snap
components/__snapshots__/province.spec.js.snap
components/__snapshots__/state.spec.js.snap
components/billing-postcode.jsx
components/delivery-postcode.jsx
components/loader.jsx
components/message.jsx
components/payment-type.jsx
components/province.jsx
components/state.jsx
demos/main.scss
partials/billing-postcode.html
partials/delivery-postcode.html
partials/loader.html
partials/message.html
partials/payment-type.html
partials/province.html
partials/state.html
test/helpers.js
test/partials/loader.spec.js
test/partials/message.spec.js
test/utils/form-element.spec.js
utils/form-element.js
utils/loader.js
utils/payment-type.js

This removes `n-ui-foundations` as a dependency.
Chose to do this because:
- There was only one package from it that we were using, which was `o-normalise`. Felt it would be simpler to add that package as a dependency ourselves.
- There was the only one utility class from n-ui-foundations we were using, which was `n-ui-hide`. However, because we were not using any mixins from `n-ui-foundations`, we would have needed the apps that use `n-conversion-forms` to apply those mixins for this class to be available. Instead we are now using our own class for hiding, `ncf__hidden`, which had already been defined.

Origami upgrade: Remove n-ui-foundations

---

components/__snapshots__/delivery-option.spec.js.snap
components/delivery-option.jsx
partials/delivery-option.html
test/partials/delivery-option.spec.js

Our tests were failing around this, so I've made a change so that we don't get type errors in the JSX component when we receive a delivery option with a value we're not expecting.
This also required a small change to the handlebars partial to display the same output as the JSX component. I'm using the `ifEqualsSome` helper from `n-handlebars` for this. However, that helper is deprecated so you will see warnings. I'm not too concerned about this, because we should be switching over to JSX soon anyway.

fix: handle when a delivery option value is not recognised.

---

styles/_shared.scss

Stylelint had an issue with prefixing an attribute selector with an element selector. This could be avoided for one of the selectors, so fixed it for that. For the other, I needed to disable stylelint for that line because it needs to override a selector in `o-forms`.

fix: sort out style linting errors.

---

main.scss

We picked the wrong heading level when migrating `o-typography`. This fixes that so that the correct size is used.

fix: use the correct font size for headers

---

main.scss

We forgot to do this when migrating to the latest o-forms, and so we were not getting any textarea styling.

fix: include textarea element when calling o-forms mixin.

---

main.scss
utils/validation.js

Two minor cosmetic changes and fix the validation code which was blocking form submission if there was a validation error in the form at all. Check the individual commits for descriptions of each change.
|  ![Screenshot 2020-01-02 at 10 14 28](https://user-images.githubusercontent.com/35035/71662456-778fd980-2d49-11ea-9330-148a60a20be9.png)      |     ![Screenshot 2020-01-02 at 10 15 33](https://user-images.githubusercontent.com/35035/71662461-7c548d80-2d49-11ea-8a28-53a152c400d9.png)   |
| ![Screenshot 2020-01-02 at 10 13 57](https://user-images.githubusercontent.com/35035/71662481-88d8e600-2d49-11ea-8bc3-01f3463824b4.png) | ![Screenshot 2020-01-02 at 10 12 14](https://user-images.githubusercontent.com/35035/71662486-8d9d9a00-2d49-11ea-9a13-9a144f181a …

Add spacing and fix validation errors

---

components/__snapshots__/delivery-option.spec.js.snap
components/delivery-option.jsx
partials/delivery-option.html

This is needed for the validation code to work. Without it the form
can't be submitted if there is a validation error. 🐿 v2.12.5

Ensure origami form inputs have titles

---

components/__snapshots__/accept-terms.spec.js.snap
components/accept-terms.jsx
partials/accept-terms.html
test/utils/validation.spec.js
utils/validation.js

The latest o-forms expects every form field to have a title and an input. When the validation is run and the error summary is calculated it pulls the textual content from the title in order to prefix against the error message (as seen in below screenshot). If the element is not there, a null reference error is thrown.
Although this PR fixes a few issues with NCF, it'd be nice if this waited for the release of the o-forms fix for summary replacement (https://github.com/Financial-Times/o-forms/pull/310) to ensure version parity.
[Ticket](https://trello.com/c/h7qtXcn9/1743-next-retention-origami)

fix: validation issues with terms changes

---

components/delivery-option.jsx
components/delivery-option.spec.js
demos/data.json
partials/delivery-option.html
test/partials/delivery-option.spec.js

As part of the Page Kit migration for `next-subscribe`, I got an error about `ifEqualsSome` not being a registered helper anymore. The only way to get the same functionality (thanks to HBS) was to move that logic to the controller and pass it in.
Ideally, the way it was done in the JSX file was the correct way. Realistically though, the HBS and JSX needs to live in parallel for a little while still so I've had to make them both function the same way to make the tests work.
[Ticket](https://trello.com/c/cMKwZJ0y/1739-next-subscribe-go-live-with-pagekit-migration)

Update delivery options to no longer use ifEqualsSome 🐿 v2.12.5

---

Makefile
components/__snapshots__/delivery-postcode.spec.js.snap
components/country.jsx
components/delivery-postcode.jsx
components/delivery-postcode.spec.js
main.scss
styles/forms-additional-field-information.scss
styles/forms-additional-field-instructions.scss

I needed to make a few adjustments in order to create the postcode checker in account settings. 
These adjustments include:
Adding functionality to determine the correct reference to postcode from the country code given
Adds additional field information. Origami does not give an option to add text below the input field so I have added this functionality here. 
It also adjusts the styling of the error message so that when a client validation fails the additional field information will move down for the error message. 
[Ticket](https://trello.com/c/rZk8pnIc/71-delivery-address-post-code-check)

Postcode checker adjustments

---

utils/validation.js

When using the Validation util, it initialises OForms for our form and that attaches an event listener to the submit handler which runs the custom validation and then submits the form programmatically upon success.
This breaks our journey on next-subscribe as we don't want to submit the form immediately - we need to wait for the iframe completion.

fix: allow optional usage of browser validation 🐿 v2.12.5

---

components/__snapshots__/payment-type.spec.js.snap
components/payment-type.jsx
partials/payment-type.html

Prevent the iframe in `next-subscribe` from overflowing.

Fix iframe overflow issue 🐿 v2.12.5

---

components/__snapshots__/payment-type.spec.js.snap
components/error-page.spec.js
components/loader.jsx
components/loader.spec.js
components/payment-type.jsx
components/payment-type.spec.js
docs/PARTIALS.md
partials/loader.html
partials/payment-type.html
test-jest/helpers/fetch-hbs-as-string.js
test/helpers.js
test/partials/error-page.spec.js
test/partials/loader.spec.js
utils/loader.js

We need to have a way of rendering a loading overlay on top of the payment types while the Zuora iframe config is fetched so as to avoid users on slow connections to submit forms without the payment information being entered.
[Ticket](https://financialtimes.atlassian.net/jira/software/projects/AC/boards/971?selectedIssue=AC-66)

Add way of showing loader on inital render of payment types

---

test/utils/delivery-option.spec.js
utils/delivery-option.js

Spreading a single node was causing an error in the `handleDeliveryOptionChange` function.
This PR adds tests to exercise the bug and fixes it.
https://financialtimes.atlassian.net/browse/CQR-24

CQR-24: Refactor handleDeliveryOptionChange to deal with single nodes 🐿 v2.12.5

---

styles/payment-term.scss

The boxes are collapsed while they should be spaced. Please check the value of o-spacing used in next-retention and let’s use that.
[Ticket](https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1035&modal=detail)
Before
After

Cqr 21 subscription options

---

package.json

For any apps consuming `n-conversion-forms`, the `main` value that currently points to `index.js` will produce this error:
> "Cannot find module '/Users/andy.gout/Documents/next-subscribe/node_modules/@financial-times/n-conversion-forms/index.js'. Please verify that the package.json has a valid \"main\" entry"
No `index.js` file exists at root level at suggested; it exists in the `dist` directory, which this PR fixes.

Amend package.json 'main' property value

---

Makefile
package.json

Rename npm script `transpile` to `build` for semantic clarity and parity with corresponding `make` command (i.e. `make build`).
Also have it run at end of npm `prepare` script.

Rename npm transpile script to build

---

.circleci/config.yml

Preceding `run` command will call `make install`, which ends with a build step that creates the `dist` and so need not be repeated.

Remove unnecessary 'make build' from .circleci/config.yml

---

components/message.jsx
partials/message.html

🐿 v2.12.5
On the account-settings pages, we have a few messages that will be shown to all users i.e `Changing details here changes your login credentials across all FT.com services`. These are `inform` messages but do not require the extra padding that o-message--inner and o-message--notice or o-message--alert supply. I have therefore added an isStaticMessge which prevents these classes from being added to the message component.
[Ticket](https://financialtimes.atlassian.net/browse/AC-77)

Adds isStaticMessge

---

components/education-job-title.jsx
partials/education-job-title.html

As part of the US growth work, we want to capture whether anyone joining the licence of an educational client is a student or faculty member. The US B2B team wants to further distinguish students between post- and under- graduates. This PR changes the "Student" option for "Graduate Student" and "Undergraduate Student" if the prop `isUSContract` is set to true.
[Ticket](https://financialtimes.atlassian.net/jira/software/projects/USG/boards/969?selectedIssue=USG-15)

Add options for US-based contracts

---

components/__snapshots__/accept-terms.spec.js.snap
components/accept-terms.jsx
main.scss
partials/accept-terms.html
test/partials/accept-terms.spec.js

- Revert accessibiliy changes to terms and conditions whilst we await Product to check with legal regarding copy approval.
[Ticket](https://financialtimes.atlassian.net/browse/AC-112?atlOrigin=eyJpIjoiY2VjZTQ1MzYyMDQ0NDY2MmEwZDYwZjM1ZDFkMjZhM2UiLCJwIjoiaiJ9)
| <img width="710" alt="image" src="https://user-images.githubusercontent.com/7748470/74549372-6e4c7c00-4f47-11ea-8844-9255f2ce18c4.png"> | <img width="710" alt="image" src="https://user-images.githubusercontent.com/7748470/74549042-d6e72900-4f46-11ea-901a-388508cf43ee.png"> |

Revert terms and conditions accessibility changes

---

components/__snapshots__/licence-confirmation.spec.js.snap
components/licence-confirmation.jsx
components/licence-confirmation.spec.js
partials/licence-confirmation.html

Adds a `isEducationalLicence` prop to the licence-confirmation component and Handlebar template, to customise the confirmation message for people signing up to a B2B licence of an educational client.
[Ticket](https://financialtimes.atlassian.net/jira/software/projects/USG/boards/969?selectedIssue=USG-15)
|![image](https://user-images.githubusercontent.com/1705375/75025921-efe66180-5493-11ea-9fb3-ab9f593619cb.png)|![Screenshot 2020-02-21 at 10 20 19](https://user-images.githubusercontent.com/1705375/75025850-ce857580-5493-11ea-8714-8bffc3b313b4.png)|

Amend confirmation message for educational clients

---

bower.json

- Fix for issue in `next-retention` were build was failing due to conflicting dependencies.

Unpin bower dependencies 🐿 v2.12.5

---

styles/customer-care.scss

Doing a search turned up instances of this only being used in `next-retention` which is where this bug was reported so it may as well be ripped out.
[Ticket](https://financialtimes.atlassian.net/browse/AC-241)
| <img width="281" alt="1583254889" src="https://user-images.githubusercontent.com/708296/75800004-d507cd00-5d70-11ea-9ecf-3bad1d8cc406.png"> | <img width="280" alt="1583254960" src="https://user-images.githubusercontent.com/708296/75800029-ddf89e80-5d70-11ea-80ac-00e7c1e3b496.png"> |

Remove teal colouring for customer care message on mobile 🐿 v2.12.5

---

components/customer-care.jsx

This partial isn't always used in a full page context so make the headers optional.
[Ticket](https://financialtimes.atlassian.net/browse/AC-246)
For example:

Make headers optional on customer care partial

---

components/message.jsx

`next-subscribe` passes links in the text for `additionalMessages`. This needs to be set dangerously for it to be rendered properly.
[Ticket](https://financialtimes.atlassian.net/browse/ACQ-115)

ACQ-115: Set additonalMessages html with dangerouslySetInnerHTML 🐿 v2.12.6

---

components/__snapshots__/accept-terms.spec.js.snap
components/__snapshots__/billing-city.spec.js.snap
components/accept-terms.jsx
components/billing-city.jsx
components/billing-city.spec.js
components/index.jsx
partials/accept-terms.html
partials/billing-city.html
test/partials/billing-city.spec.js
utils/billing-city.js

ePaper will be sold as a separate and solely product.
The buy flow pages/sign up forms might need few tweaks to cater for some of the ePaper specifics
https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1035&projectKey=ACQ&modal=detail&selectedIssue=ACQ-87
related to: https://github.com/Financial-Times/next-subscribe/pull/1026

ACQ-87: add billing city fields (for epaper) 🐿 v2.12.6

---

components/message.jsx

Very similar to https://github.com/Financial-Times/n-conversion-forms/pull/415.
`next-subscribe` passes links in the text for `message`. This needs to be set dangerously for it to be rendered properly.
[Ticket](https://financialtimes.atlassian.net/browse/ACQ-115)

ACQ-115: Set message text html with dangerouslySetInnerHTML 🐿 v2.12.6

---

components/trial-banner.jsx

It was outputting [object Object] previously

ACQ-170: Fix trial banner trialDuration rendering

---

components/trial-banner.jsx

Related to https://github.com/Financial-Times/n-conversion-forms/pull/419.
Concatenating `' '` to the span causes the same issue. This fixes it.

Fix white space on trial banner 🐿 v2.12.6

---

components/__snapshots__/debug.spec.js.snap
components/accept-terms.jsx
components/debug.jsx
demos/init-jsx.js
partials/accept-terms.html
partials/debug.html

During Print trials, subscribers are not eligible to receive credits for non-received newspaper copies (in case of delivery complaints or suspended subscriptions).
This fact shall be clearly stated to user before completing the SignUp journey
###Ticket
https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1035&projectKey=ACQ&modal=detail&selectedIssue=ACQ-177

ACQ-177: Print trial t and c

---

components/__snapshots__/licence-confirmation.spec.js.snap
components/licence-confirmation.jsx
components/licence-confirmation.spec.js
partials/licence-confirmation.html
secret-squirrel.js

- copy for the bottom link on `licence-confirmation` has been changed to "Start reading"
- add `contentId` prop to `licence-confirmation` allowing the start reading link to point at articles

ACQ-180 Add article linking to licence-confirmation component

---

components/__snapshots__/fieldset.spec.js.snap
components/fieldset.jsx
components/fieldset.spec.js

Changes Fieldset header to be of proptype node rather than elementType so that markup can be passed to the header (this allows us to include visually hidden text as required in this ticket: https://financialtimes.atlassian.net/browse/ACQ-121)

Update Fieldset header to be of type node 🐿 v2.13.0

---

components/country.jsx

filterList should be an array of strings (country codes) not an array of objects. You can see it is used in `utils/countries.js` (as `filter`) as follows:
`data = data.filter(item => filter.includes(item.code));`
This was spotted as part of https://financialtimes.atlassian.net/browse/ACQ-122 when migrating the offer / details page which uses this component.

Fix filterList proptype to be array of strings (country codes) 🐿 v2.13.0

---

components/country.jsx
components/delivery-postcode.jsx

fixes a spelling mistake on DeliveryPostCode component. 
Changes property spelling from `additonalFieldInformation` to `additionalFieldInformation`
**THIS IS A BREAKING CHANGE** ❗

fix!: correct DeliveryPostCode misspelled property

---

components/__snapshots__/delivery-start-date.spec.js.snap
components/delivery-start-date.jsx
components/delivery-start-date.spec.js
partials/delivery-start-date.html

The PR adds support for address update messages to DeliveryStateDate Component 
[Ticket](https://financialtimes.atlassian.net/browse/ACC-401)
| Before |
| ------ |
|<img width="500" alt="Screenshot 2020-06-03 at 18 09 35" src="https://user-images.githubusercontent.com/17183724/83666833-76e3c380-a5c5-11ea-973d-9de97f894ba6.png">| 
| After (Default - Same as before) |
| ------ |
|<img width="500" alt="Screenshot 2020-06-03 at 18 09 35" src="https://user-images.githubusercontent.com/17183724/83666960-9e3a9080-a5c5-11ea-893c-c18c805b188e.png">| 
| After (when isAddressUpdate) | 
| ------ |
|<img width="500" alt="Screenshot 2020-06-03 at 18 22 01" src="https://user-images.githubusercontent.com/17183724/83667991-2e2d0a00-a5c7-11ea-875e-dae44d749987.png">|
| After (when isAddressUpdate and …

ACC-401 Improve Messages in DeliveryStateDate Component 

---

components/delivery-instructions.jsx
demos/data.json
demos/init-jsx.js
partials/delivery-instructions.html
test/partials/delivery-instructions.spec.js

“Either add them to the Security Notes section at ft.com/myaccount after purchase, or contact FT Customer Care.” shall be visible on the SignUp only.
It shall not be visible when user logs into MMA (because user is already logged in ft.com/myaccount and sees "Security Notes")
https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1035&projectKey=ACQ&modal=detail&selectedIssue=ACQ-233
before
after

ACQ-233: add optional signup security note 🐿 v2.13.0

---

components/billing-country.jsx
components/country.jsx
components/payment-term.jsx

PropType definitions for billingCountry and PaymentTerm were wrong, PaymentTerm.option.discount should be a boolean, and BillingCountry.filterList an array of strings
errors from `next-subscribe`:
```
Warning: Failed prop type: Invalid prop `paymentTerms[0].discount` of type `boolean` supplied to `Payment`, expected `string`.
in Payment
Warning: Failed prop type: Invalid prop `options[0].discount` of type `boolean` supplied to `PaymentTerm`, expected `string`.
in PaymentTerm (at payment.jsx:79)
in Payment
Warning: Failed prop type: Invalid prop `filterList[0]` of type `string` supplied to `BillingCountry`, expected `object`.
in BillingCountry (at payment.jsx:83)
in Payment
```
might help with the build issues of https://github.com/Financial-Times/next-subscribe/pull/1187
Have you …

ACQ-123 BillingCountry and PaymentTerm JSX proptype fixes

---

bower.json
components/__snapshots__/accept-terms.spec.js.snap
components/__snapshots__/email.spec.js.snap
components/__snapshots__/licence-header.spec.js.snap
components/accept-terms.jsx
components/accept-terms.spec.js
components/email.jsx
components/email.spec.js
components/licence-header.jsx
components/licence-header.spec.js
docs/PARTIALS.md
package.json
partials/accept-terms.html
partials/email.html
partials/licence-header.html
styles/accept-terms.scss

We are soon going to be inviting users to sign up via a new type of licence: a B2C Partnership Licence.  Users will be purchasing access to the FT as part of a bundle with, for example, the Washington Post.  They will click on a URL that the Partner sends them and be taken to a customised sign up form, and so we need to alter some components that will be shown on the form.
I have altered the `email` component so that if a user is trying to sign up on a B2C Partnership Licence they are asked for their `email address` (no reference to work). They also get a different form header: this update removes and reference to trials and companies, as per the screenshots below.  The `accept-terms` component also now renders a simplified terms and checkbox. …

Change licence-header and email components for us with B2C Partnerships

---

components/__snapshots__/payment-term.spec.js.snap
components/payment-term.jsx
package.json
partials/payment-term.html
test/partials/payment-term.spec.js

* Fixes the version of `graceful-fs`, so the app dependencies are installed correctly when using Node 12+ (mocha and jest fail otherwise)
* Changing the `Try the FT` trial copy to `Trial: Premium Digital`
https://financialtimes.atlassian.net/browse/ACQ-485

ACQ-485 payment term wording for trial

---

.babelrc
package.json

Since our code uses async / await, ensure the runtime is included to support it.

fix: reintroduce babel-transform-runtime to stop build errors

---

components/__snapshots__/b2c-partnership-licence-confirmation.spec.js.snap
components/b2c-partnership-licence-confirmation.spec.js

Adds a very basic and not interesting test that was missing from #444

Add test for b2cpartnership confirmation component

---

README.md
components/__snapshots__/b2c-partnership-confirmation.spec.js.snap
components/b2c-partnership-confirmation.jsx
components/b2c-partnership-confirmation.spec.js

If FT is the B2CP vendor, one confirmation is shown. If the vendor is WaPo, another confirmation is shown
There are 2 types of B2C Partnership.  
- If FT is the vendor, we show one confirmation page after the subscription is purchased.
- If FT is the partner, we show a different confirmation page after the user has registered their 3-month access.
[Ticket](https://financialtimes.atlassian.net/browse/UG-208)
Screenshots are from the storybook, so will look better when the components are implemented in `next-subscribe` :)
| ![image](https://user-images.githubusercontent.com/25018001/91989947-06198800-ed29-11ea-97b0-facb178c83ef.png) | ![image](https://user-images.githubusercontent.com/25018001/91990019-20536600-ed29-11ea-997f-379fa349324c.png) |
Have …

Offer different b2cp-confirmation component for when FT is vendor

---

components/company-name.jsx

Adds a placeholder to the companyName field so that it doesn't just say 'undefined'
None - spotted bug.  Now consistent with other fields
|![image](https://user-images.githubusercontent.com/25018001/92251526-e28b4480-eec4-11ea-8425-370838b09d5d.png)| ![image](https://user-images.githubusercontent.com/25018001/92251196-61cc4880-eec4-11ea-9ba6-d3f8fc7c3596.png)|

add a placeholder to the companyName field

---

components/__snapshots__/b2c-partnership-confirmation.spec.js.snap
components/__snapshots__/confirmation.spec.js.snap
components/b2c-partnership-confirmation.jsx
components/b2c-partnership-confirmation.spec.js
components/confirmation.jsx
components/confirmation.spec.js

Basically undoes #455 and adjusts the current confirmation component for subscriptions bought.
There are 2 types of B2C Partnership.  
- If FT is the vendor, we show one confirmation page after the subscription is purchased.
- If FT is the partner, we show a different confirmation page after the user has registered their 3-month access.
[Ticket](https://financialtimes.atlassian.net/browse/UG-208)
| ------ | ------ |
|![image](https://user-images.githubusercontent.com/25018001/92131124-7bef2380-edfd-11ea-92a5-c7571e31af56.png) | ![image](https://user-images.githubusercontent.com/25018001/92131276-b5279380-edfd-11ea-9022-0d3b28ce778d.png) |
Example of a B2CPartnership Conf:
Ye, obvs

 USG-208 Update the B2C Partnership Confirmation Component (again)

---

components/__snapshots__/licence-header.spec.js.snap
components/__snapshots__/licence-title.spec.js.snap
components/licence-title.jsx

Change licence title for B2B sign-in forms with not presented display name of the company
https://financialtimes.atlassian.net/browse/ACQ-550
| <img src="https://user-images.githubusercontent.com/30728763/92238468-00a37580-eec2-11ea-8416-4bdae8eac51c.png" width=350px/> |   <img src="https://user-images.githubusercontent.com/30728763/92238264-81ae3d00-eec1-11ea-8e68-bdca1751294b.png" width=350px />   |
| <img src="https://user-images.githubusercontent.com/30728763/92249997-8f6cbe00-eed3-11ea-9578-a398452ddb40.png" width=350px/> |   <img src="https://user-images.githubusercontent.com/30728763/92250093-b4613100-eed3-11ea-9beb-f8f361067b15.png" width=350px/>

ACQ-550 Change licence title for B2B sign-in forms with not presented company name

---

.eslintrc.js
.gitignore
package.json

This got removed in the #465 but tests should be run before committing.
ESLint dependency has been added to fix unit tests. Related PR for same fix: https://github.com/Financial-Times/next-tour-page/pull/291

Reintroduce make test to pre-commit husky hook 🐿 v2.13.0

---

components/education-job-title.jsx

Previously there was no control on the storybook for `isUSContract`. This is now added:
So we can see the educationalJobTitles available in the US.

add `isUSContract` propType

---

components/__snapshots__/confirmation.spec.js.snap
components/confirmation.jsx
components/confirmation.spec.js
main.scss

This PR enables users that hit the 'Bernie barrier' to return to the article they were reading after signing up to the $1 trial.
[Voila!](https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1128&projectKey=UG&modal=detail&selectedIssue=UG-254)
| ![image](https://user-images.githubusercontent.com/25018001/93819015-0be0fa00-fc53-11ea-8006-d4663837dee3.png)|![image](https://user-images.githubusercontent.com/25018001/93818991-01befb80-fc53-11ea-8488-0ea0d55900bb.png)|
- [n/a now that storybook exists] **Documentation** updated or created

UG-254 add CTA to return user to article they were reading

---

components/__snapshots__/graduation-date.spec.js.snap
components/graduation-date.jsx

Graduation date component 'Month' and 'Year' labels need more context
https://github.com/Financial-Times/n-conversion-forms/issues/469

Add more context to graduation date component labels

---

components/__snapshots__/confirmation.spec.js.snap
components/confirmation.jsx

The return-to-article Cta buttons in the confirmation component are not centred when used inside the next-subscribe app.
Blocking this ticket:
https://financialtimes.atlassian.net/browse/UG-254
|      
|     
|

Center return to article Cta buttons

---

components/__snapshots__/industry.spec.js.snap
components/__snapshots__/position.spec.js.snap
components/__snapshots__/responsibility.spec.js.snap
components/industry.jsx
components/position.jsx
components/responsibility.jsx

As a part of B2C Prefenect AB testing, we would like to rename new variant data-tracking fields for the Preference section to make it consistent with the existing Preference fields. See requirement documentation on Control and Variant actions https://docs.google.com/spreadsheets/d/13AvBzMiH4Syq0o2sjhSsNi5euTpIASUTFvaWy5C27To/edit?usp=sharing
https://financialtimes.atlassian.net/browse/ACQ-526 

Rename preferences trackable fields

---

components/__snapshots__/graduation-date.spec.js.snap
components/graduation-date.jsx
components/graduation-date.spec.js
main.scss
styles/graduation-date.scss

Update compliance text for Graduation date picker. The whole text should look like : 
We use the information you provide, and may share it with your institution, for the purposes of administering your institution’s licence for FT.com. 
We may also use it to ensure our communications to you are more relevant.  If you do not wish us to do so, you can amend your preferences at any time here
https://financialtimes.atlassian.net/browse/ACQ-608
|  <img src="https://user-images.githubusercontent.com/30728763/95365673-206ff400-08db-11eb-889d-1315c7197867.png" width=250px /> |  <img src="https://user-images.githubusercontent.com/30728763/95365834-4f866580-08db-11eb-98a2-63a2333c8ffb.png" width=250px /> |
Have you completed these common tasks (remove those that …

[ACQ-608] Updated compliance text for graduation component

---

components/__snapshots__/confirmation.spec.js.snap
components/confirmation.jsx
components/confirmation.spec.js
components/confirmation.stories.js
main.scss

Tailor the FT to meet your goals!
As iteration 1 of the new [Activation Journey](https://ftnext.invisionapp.com/share/VSYOMW245BA#/screens/430946496), users will simply be taken to myFT on clicking the 'Tailor the FT to meet your goals' link.  This PR updates the confirmation component to include that button  when it's provided. The implementation is deliberately flexible so that the new `nextActionTop` prop can provide this component with anything, should we wish to alter what's used as the next action.
These screenshots are from the storybook and hence look weird 😂  but they do show the new button.
|![image](https://user-images.githubusercontent.com/25018001/95753143-12cebb80-0c99-11eb-91ce-3c12713a2fe1.png)|![image](https://user-images.githubusercon …

UG-286 Update confirmation component to show a ‘Tailor the FT..." button

---

components/payment-term.jsx
components/payment-term.spec.js
components/payment-term.stories.js

A lite subscription gives access to the subset of the FT for a fraction of the cost of a regular sub. Due to the low cost of the subscription, we don’t want to subscription to auto-renew.
Amends the payment-term component to remove mentions of auto-renewal if the offer is fixed term (e.g. in the case of lite subscription).
See https://github.com/Financial-Times/next-subscribe/pull/1416 for more info.
https://financialtimes.atlassian.net/browse/UG-317
| Basic component | Fixed-term offer |
|  ![Screenshot 2020-11-24 at 11 45 29](https://user-images.githubusercontent.com/1705375/100090174-af64ab80-2e4a-11eb-94e5-d4fde8573fff.png)|![Screenshot 2020-11-24 at 11 45 44](https://user-images.githubusercontent.com/1705375/100090205-b986aa00-2e4a-11eb-9814-46ed1de57c3c.png)|
Have …

UG-317 Customise payment-term component for lite subs

---

components/__snapshots__/message.spec.jsx.snap
components/message.jsx
components/message.spec.jsx

We have some Messages rendered inside an IFRAME and clicking on them, leads to even more serious issues, than not loading in the `_top` frame - we get rejected by Access service based off referer and users see an error screen instead of the actual login.
* openning in a new tab/window solves this, since referer URL is empty then
https://financialtimes.atlassian.net/browse/ACQ-734

[ACQ-734[ Added ability to set Message target property

---

components/licence-confirmation.jsx

This extends the capability of the LicenceConfirmation component to alter the CTA for B2B users who join their company's licence.
It will be used by the activation journey to send users to `/activate/bundles` on completion of their journey through `next-subscribe`.
|![image](https://user-images.githubusercontent.com/25018001/102373827-84d4c100-3fb8-11eb-8584-ee0d029170a3.png)|![image](https://user-images.githubusercontent.com/25018001/102373745-71295a80-3fb8-11eb-8d45-2da553559f82.png)|

UG-341: extend LicenceConfirmation to take a different CTA

---

components/__snapshots__/b2c-partnership-confirmation.spec.js.snap
components/b2c-partnership-confirmation.jsx
components/b2c-partnership-confirmation.spec.js
components/b2c-partnership-confirmation.stories.js

This extends the capability of the B2CPartnershipConfirmation component to alter the CTA for B2C Partnership users who join the partner's licence.
It will be used by the activation journey to send users to `/activate/bundles` on completion of their journey through `next-subscribe`.
TBC
|![image](https://user-images.githubusercontent.com/25018001/102532781-60eaab80-409c-11eb-8684-acf001676d09.png)|![image](https://user-images.githubusercontent.com/25018001/102532961-ad35eb80-409c-11eb-846b-15f1c6fffa1e.png)|

extend B2CPartnershipConfirmation to take a different CTA

---

components/payment-term.jsx
test/utils/payment-term.spec.js
utils/payment-term.js

Add base amount in a data attribute (without currency) for PSD2 requirements.
[ticket](https://financialtimes.atlassian.net/browse/ACQ-761)

ACQ-761 Add base amount getter for PSD2

---

components/__snapshots__/delivery-address-type.spec.js.snap
components/__snapshots__/delivery-po-box.spec.js.snap
components/delivery-address-type.jsx
components/delivery-address-type.spec.js
components/delivery-address-type.stories.js
components/delivery-po-box.jsx
components/delivery-po-box.spec.js
components/delivery-po-box.stories.js
components/index.jsx

As part of US Print Offer Delivery implementation, two new components are added to comply with [Requirements](https://docs.google.com/document/d/1UF3-kRDVATzUuOePEtulcT1lXoZtfdKCztkUgdGtFm0/edit#heading=h.6e0cccq3jiaw) and [Design Document](https://ftnext.invisionapp.com/share/V5Y6GTC4FEJ#/screens/427782519)
These new components will be used by `next-subscribe`.
https://financialtimes.atlassian.net/browse/ACQ-751
Address type component at `Storybook`
P.O. Box field component at `Storybook`

ACQ-751: Adding new components for US delivery Print Offers

---

README.md
utils/zuora.js

This is a part of  [Ticket](https://financialtimes.atlassian.net/browse/ACQ-878)
As we only have access to those zuora related methods that we expose through n-conversion-forms. In n-conversion-forms we standardized access to the methods we use in other projects. I have added setAgreement here as it will need to be used on next-subscribe

ACQ-878 Add Zuora setAgreement method

---

components/__snapshots__/delivery-postcode.spec.js.snap
components/delivery-postcode.jsx
components/delivery-postcode.spec.js
components/delivery-postcode.stories.js
utils/validation.js

Adding an url to allow modify postcode by redirecting to first step of subscription. Additionally a fine tune was made on validation component to prevent bouncing.
https://financialtimes.atlassian.net/browse/ACQ-751

Acq 751 add change delivery postcode link

---

components/__snapshots__/delivery-instructions.spec.js.snap
components/delivery-instructions.jsx
components/delivery-instructions.stories.js

Changes related to change of distributor for print subscription
[ACQ-873](https://financialtimes.atlassian.net/browse/ACQ-873)
The change can be seen via next-subscribe locally https://local.ft.com:5050/buy/offer/testprint/details But n-conversion-forms should be built and linked in next-subscribe first

ACQ-873 change of distributor from EDG to News UK 

---

components/delivery-instructions.jsx

This is a patch to the UK distributor changes. Changed the line
```
const maxLengthText = maxlength && country !== 'GBR'? ` (Max. ${maxlength} characters)` : '';
```
to `&& country === 'GBR` 
because we need to pass in the country to remove the `plastic bag` part of the message. And if we do that, then the line above would forcibly remove the `max characters` message because the country *was* GBR.

Fixed the logic around max characters

---

components/delivery-instructions.jsx

We need to add Max. characters for US and Canada delivery instructions. The previous PR has added max. characters instructions for UK, which was correct, but conditional removed it from US and Canada. This is a quick fix related to [PR](https://financialtimes.atlassian.net/browse/ACQ-873)

Add maxLengthText for US and Canada

---

components/__snapshots__/google-sign-in.spec.js.snap
components/google-sign-in.jsx
components/google-sign-in.spec.js
components/google-sign-in.stories.js
components/index.jsx
main.scss
styles/google-sign-in.scss

Adding a GoogleSignIn button for the Google extender meter functionality.
https://financialtimes.atlassian.net/browse/ACQ-866
Designs: https://www.figma.com/proto/DMlyoknFg5Gg4zt66qcy3Z/google-integration?node-id=7%3A353&viewport=359%2C345%2C0.45831066370010376&scaling=scale-down
| Mobile | Web |
| ![image](https://user-images.githubusercontent.com/13876273/112352929-81de2080-8ccb-11eb-8d24-1d2029c067bb.png) | ![image](https://user-images.githubusercontent.com/13876273/112353030-9f12ef00-8ccb-11eb-8d7a-35d55cf860d2.png) |

ACQ-866: Adding a GoogleSignIn button component with styles.

---

components/__snapshots__/billing-city.spec.js.snap
components/__snapshots__/debug.spec.js.snap
components/billing-city.jsx
components/debug.jsx

fix the billing postcode component to allow hide including its title label. Also include a modification on the debug bar to fill the form depending on the country
https://financialtimes.atlassian.net/browse/ACQ-752
When it need to be shown
When it need to be hidden
Before fix

ACQ-752: fix the billing postcode component to allow hide completely

---

components/__snapshots__/google-sign-in.spec.js.snap
components/google-sign-in.jsx
styles/google-sign-in.scss

Testing Google registration flow for ACQ-867 I noticed we need some small fixes on the google widget (sign-in button).
- A small fix on padding spaces
- To redirect page but in parent window, because the button is included in an iframe.
- Original: https://financialtimes.atlassian.net/browse/ACQ-866
- Current implementation: https://financialtimes.atlassian.net/browse/ACQ-867
|  https://user-images.githubusercontent.com/13876273/113262805-506be300-92d1-11eb-9a7f-f941ad7145fe.mov  |  https://user-images.githubusercontent.com/13876273/113262846-5cf03b80-92d1-11eb-84d2-8e6393ad9087.mov  |

ACQ-867: Small css fixes and to redirect page in parent window

---

components/industry.jsx
components/industry.spec.js
components/job-title.jsx
components/job-title.spec.js
components/phone.jsx
components/phone.spec.js
components/position.jsx
components/position.spec.js
components/responsibility.jsx
components/responsibility.spec.js

Working on a `whilte-label` registration form, required some of the existing registration components to allow for dynamic `required` state property.
Changed components:
* `Industry` component's title now has the `optional` additional class
* `JobTitle` has `isRequired` property and `optional` title class
* `Phone` has `isRequired` property and `optional` title class
* `Positon` has an additional `optional` title class
* `Resposnbility` has `isRequired` and `fieldLabel` and `optional` title class
https://financialtimes.atlassian.net/browse/ACQ-885

[ACQ-885] White-label design implementation

---

styles/google-sign-in.scss

After deploy to production, we can see some differences between local dev and prod when barrier is display in desktop browsers. This PR solves the button style issues on prod. 
https://financialtimes.atlassian.net/browse/ACQ-867
| ![Screenshot 2021-04-13 at 16 59 33](https://user-images.githubusercontent.com/13876273/114576064-16102780-9c7b-11eb-89eb-cc9e9e93aa57.png) | ![Screenshot 2021-04-13 at 16 59 10](https://user-images.githubusercontent.com/13876273/114576122-23c5ad00-9c7b-11eb-941e-ecb03314417c.png) |
In addition, new views on Mobile and Tablet mode.
| Mobile | Tablet |
| ![Screenshot 2021-04-13 at 17 01 38](https://user-images.githubusercontent.com/13876273/114576326-52438800-9c7b-11eb-91ba-1ca1ea163a6e.png) | ![Screenshot …

ACQ-867: small style fixes after check in prod.

---

components/payment-term.jsx

This is a quick fix (but not elegant from my point of view) in order to unblock go live today with an “ePaper 3 month intro offer global” offer today.
Complete discussion: https://financialtimes.slack.com/archives/CSVRXFV6F/p1618415641326700
https://financialtimes.atlassian.net/browse/ACQ-925
| ![Screenshot 2021-04-15 at 10 01 07](https://user-images.githubusercontent.com/13876273/114837096-9f3a7200-9dd3-11eb-9b49-b9aa9e13e792.png) | ![Screenshot 2021-04-15 at 10 01 23](https://user-images.githubusercontent.com/13876273/114837116-a792ad00-9dd3-11eb-8d75-c2e5e0dc5b11.png) |

ACQ-925: Adding isEpaper property to filter (avoid) Trial Premium title.

---

components/__snapshots__/package-change.spec.js.snap
components/package-change.jsx
components/package-change.spec.js
components/package-change.stories.js
styles/package-change.scss

Added optional prop `introText` to PackageChange. If present, it'll render it as secondary text below the package name.
https://financialtimes.atlassian.net/browse/UG-431
|<img width="649" alt="before" src="https://user-images.githubusercontent.com/7011304/114195893-c95de100-9948-11eb-9978-eb23e9ef1e4f.png">|<img width="676" alt="after" src="https://user-images.githubusercontent.com/7011304/114195978-d8449380-9948-11eb-9cd8-f914224d447f.png">|

Add introText property to PackageChange

---

components/__snapshots__/delivery-address.spec.js.snap
components/__snapshots__/delivery-instructions.spec.js.snap
components/delivery-address.jsx
components/delivery-instructions.jsx
utils/delivery-option-messages.js

Some components adjustments coming from smoke testing of the [Print subscription for US and CAN](https://financialtimes.atlassian.net/browse/ACQ-326)
Details about the change needed [here](https://docs.google.com/document/d/1Wwnc0Q0JywY85pmEXJ-N7ZVx7EFkyoHGUOyb--YofTU)
https://financialtimes.atlassian.net/browse/ACQ-924
The screenshot of the results will defer in the fonts used, since it was tested locally
Canada
- NB note not present for US and CAN
|![image](https://user-images.githubusercontent.com/48696369/114912348-44fed880-9df6-11eb-8914-560cf36e3d9f.png)  |![image](https://user-images.githubusercontent.com/48696369/114907514-850f8c80-9df1-11eb-9849-b7581dcfa32c.png) 
- Address line 3 replaced by Apt/Floor/Suite and moved to the second position …

ACQ-924: few adjustments for print subscription requirements

---

components/__snapshots__/delivery-start-date.spec.js.snap
components/delivery-start-date.jsx
test/utils/delivery-start-date.spec.js
utils/delivery-start-date.js

Not all browsers support `input type=date`. One of those is Safari. It looks like it's in the works - the preview version does have it. But meanwhile users on Safari are left wondering what date format to use.
This PR adds an ID to the Start Date picker *title* so that we can access the title and update it to read "Delivery start date (YYYY-MM-DD)" on browsers that don't support `date` input type. 
This has already been done for Adding Suspension as that uses a custom date picker - see here for implementation details. https://github.com/Financial-Times/next-profile/pull/594. 
This PR also plugs the checking functionality into utils so that the users across all repos benefit from explicit format prompt if needed. 
https://financialtimes.atlassian.net/browse/ACC-1037
This PR does not …

ACC-1037 Added id to "Delivery start date" title span

---

styles/payment-type.scss

Icons for payment buttons, started to dissapear randomly, the path for them was checked via https://www.ft.com/__origami/service/image/v2/docs/url-builder and we conclude that needed to be modified as follow:
https://www.ft.com/assets/third-party/****** --> https://www.ft.com/__assets/creatives/third-party/******

fix payment icons path for paypal and direct debit

---

components/delivery-address-type.stories.js
components/delivery-option.stories.js
components/payment-term.stories.js
main.scss
styles/payment-term.scss

The `bigRadioButton` override mixin is currently affecting all instances of `.o-forms-input--radio-round` that has a parent with a class of `.ncf`. This created some style issues when using the `DeliveryAddressType` component within the `next-profile`. This PR ensures the `bigRadioButton` override mixin is only defined within the necessary classes.
[ACC-1031](https://financialtimes.atlassian.net/browse/ACC-1031)
| ![image](https://user-images.githubusercontent.com/893208/117684067-8ba0e200-b1ac-11eb-9008-9edbd04b7de5.png) | ![image](https://user-images.githubusercontent.com/893208/117683624-2d73ff00-b1ac-11eb-862b-915fc5341237.png) |
| ![image](https://user-images.githubusercontent.com/893208/117684017-817ee380-b1ac-11eb-8de1-97a3ce814a4a.png) | …

Fix generous radio input style override

---

components/__snapshots__/trial-banner.spec.js.snap
components/trial-banner.jsx

this url was incorrect: https://www.ft.com/__origami/service/image/v2/images/raw/https%3A%2F%2Fwww.ft.com%2Fassets%2Fb2b%2Fmacron-desktop-banner.png?source=conversion&height=40
and has been updated per @ekocian advice.
Spotted when doing: 
https://financialtimes.atlassian.net/browse/NOPS-823
|![image](https://user-images.githubusercontent.com/25018001/118121210-09e9c800-b3e9-11eb-9c5d-34de1bf19e30.png)|      ![image](https://user-images.githubusercontent.com/25018001/118121675-ba57cc00-b3e9-11eb-8ee9-e1cd9a9e52fb.png)|
(from storybook)

NOPS-823 Fix location of Emmanuel Macron image

---

components/__snapshots__/confirmation.spec.js.snap
components/__snapshots__/registration-confirmation.spec.js.snap
components/confirmation.jsx
components/lite-sub-confirmation.jsx
components/registration-confirmation.jsx

It was reported that a user didn't manage to reach their account settings after successfully buying an offer.
We changed the URL leading to account settings to https://www.ft.com/myaccount/personal-details
https://financialtimes.atlassian.net/browse/ACQ-963

ACQ-963. Change URL leading to account settings

---

utils/delivery-start-date.js

Not a proper solution (the method is still called needlessly but doesn't do anything), but until we fix it properly this should prevent the repeated calls and the rateLimiting kicking in.
We need to go thought the whole custom validation thing and figure out how to trigger it ONLY when related field is changed.
We'll keep https://financialtimes.atlassian.net/browse/ACQ-995 open to come up with a proper fix.
https://financialtimes.atlassian.net/browse/ACQ-995

ACQ-995: prevent repeated useless calls to check availability endpoint

---

.circleci/config.yml

Remove ft-next-webhooks from the repo and check and remove the Deploy hook add-on from the Heroku app. More information in the ticket
https://financialtimes.atlassian.net/browse/ACQ-1010

ACQ-1010. Remove ft-next-webhooks from the repo

---

components/__snapshots__/email.spec.js.snap
components/email.jsx
components/email.spec.js

Allow hide title for email component. This is aim to cover a specific requirement in https://financialtimes.atlassian.net/browse/ACQ-972
https://financialtimes.atlassian.net/browse/ACQ-1007 and https://financialtimes.atlassian.net/browse/ACQ-972

ACQ-1007: add possibility to hide title for email component

---

components/__snapshots__/email.spec.js.snap
components/email.jsx

Hiding email title instead of not rendering it helps on building error messages.
https://financialtimes.atlassian.net/browse/ACQ-1077

ACQ-1077: hiding email title instead of not rendering

---

components/payment-type.jsx
components/payment-type.stories.js
styles/payment-type.scss

I updated the PaymentType function to accept a new variable so that I'm able to disable Paypal when needed and replace it with the error message. 
https://financialtimes.atlassian.net/browse/ACC-873
**Before** 
**After**
**How it looks in next-profile**

ACC-873 - Created Paypal error message

---

.circleci/config.yml

Our CircleCi builds are failing. As pointed out by @meel-io in #567, [CircleCi couldn't find our `provision` as a valid step](https://github.com/Financial-Times/n-conversion-forms/pull/567/files#r678181477). We shouldn't need the provision step for this config.

Fix .circleci/config.yml

---

components/__snapshots__/accept-terms.spec.js.snap
components/__snapshots__/payment-term.spec.js.snap
components/accept-terms.jsx
components/payment-term.jsx
components/payment-term.spec.js
components/payment-term.stories.js

Changes the payment-term component to show the Light subscription offer name. See [here](https://financialtimes.atlassian.net/browse/UG-534) for more info.
https://financialtimes.atlassian.net/browse/UG-541
|     
|    
|

UG-541 — Show Light Subscription Offer name

---

.circleci/config.yml
components/lite-sub-confirmation.jsx
components/lite-sub-confirmation.stories.js
main.scss

Applied changes to the `LiteSubConfirmation` component, which renders on the Confirmation page after a successful subscription to a LiteSub.
- Removed HTML markup for the newsletter section.
- Added a list of features included with the Digital subscription
- Added button to go to ft.com
- Added instructions to cancel the subscription
https://financialtimes.atlassian.net/browse/UG-565
|<img width="358" alt="UG565-before" src="https://user-images.githubusercontent.com/7011304/126615339-db247431-420a-418b-b6a0-de2fef3efd45.png">|<img width="370" alt="UG565" src="https://user-images.githubusercontent.com/7011304/126996999-684e64dc-1ca1-4727-bb62-cc458af12b44.png">|
This code depends on [UG-564.](https://github.com/Financial-Times/n-membership-sdk/pull/477) …

UG-565: Remove the newsletter list from the lite-sub confirmation page

---

components/__snapshots__/payment-term.spec.js.snap
components/payment-term.jsx
components/payment-term.spec.js
components/payment-term.stories.js
main.scss
styles/_shared.scss
styles/payment-term.scss

As part of [ACC-998](https://financialtimes.atlassian.net/browse/ACC-998), this PR adds some new style options to the `PaymentTerm` component. This includes:
- Larger price size with prop `largePrice`
- Hide legal copy with `showLegal={false}`
- Have options appear in a row for larger screen sizes with `optionsInARow`
- Control the name of the payment term option with `title` and `subTitle` keys
- Prepend "Best offer - " to discount with `bestOffer: true` for each option
- Control the last line text with `chargeOnText` for each option
This PR also fixes a small graphical issue where the radio button and discount would move slightly when an option is selected / not selected.
https://financialtimes.atlassian.net/browse/ACC-998
Large screen:
Small screen:
Have you completed these common …

ACC-998: Implement single term subscription into PaymentTerm component

---

components/__snapshots__/payment-term.spec.js.snap
components/payment-term.jsx
components/payment-term.spec.js

A small bug sneaked in where if an option does not use the `nameMap`, it will break building a `defaultTitle`.

ACC-998: Fix PaymentTerm bug where name is undefined

---

components/__snapshots__/accept-terms.spec.js.snap
components/__snapshots__/payment-term.spec.js.snap
components/accept-terms.jsx
components/accept-terms.spec.js
components/payment-term.jsx
styles/payment-term.scss

Add a new term to AcceptTerms for single term subscriptions in transition. Update styles to PaymentTerm as when options are in a row, they were ever so slightly misaligned (`baseline` can be misleading).
https://financialtimes.atlassian.net/browse/ACC-1000

ACC-1000: Add new term to AcceptTerms and tweak styles of PaymentTerm

---

components/__snapshots__/progress-indicator.spec.js.snap
components/progress-indicator.jsx
components/progress-indicator.spec.js
components/progress-indicator.stories.js

Provides an option to remove the links on completed items in the progress indicator.
[ACQ-1143](https://financialtimes.atlassian.net/browse/ACQ-1143)
https://github.com/Financial-Times/next-subscribe/pull/1861
|![Screenshot 2021-09-01 at 17 33 34](https://user-images.githubusercontent.com/45561255/131709307-d756965d-2e93-4117-8733-368f31144aff.png)|![Screenshot 2021-09-01 at 17 33 49](https://user-images.githubusercontent.com/45561255/131709349-11ccbb0b-3592-4edf-ab6c-a61ecc5d5059.png)|

ACQ-1143 Provides an option to remove the links in the progress indicator

---

components/__snapshots__/payment-type.spec.js.snap
components/payment-type.jsx
components/payment-type.spec.js
styles/payment-type.scss

Adding checkbox option to display payment details faster for future transactions. This is a feature for single term subscription
https://financialtimes.atlassian.net/browse/ACC-1001

acc-1001 Adding checkbox option to display payment details faster

---

package-lock.json
package.json

Add @financial-times/eslint-config-next as a devDependency.
Relates to #585.

Fix missing eslint dependency

---

.circleci/config.yml
.github/workflows/gh-pages-deploy.yml
package-lock.json
package.json

When merging #590 deployment to github pages failed because the npm version used in gh-pages-deploy.yml defaulted to 6.x. This PR attempts to fix that by using node 14.
[ACQ-1330](https://financialtimes.atlassian.net/browse/ACQ-1330)

ACQ-1330 attempt to fix gh-deploy failure by using node 14

---

.github/workflows/gh-pages-deploy.yml

Due to this part of the error message in the deployment logs ![Screenshot 2021-11-19 at 12 22 13](https://user-images.githubusercontent.com/45561255/142622257-6dc29c6b-eb35-4b42-9338-00dcdea5fefb.png) this PR tries to explicitly install npm 7 in the github pages. Very trial and error.
[ACQ-1330](https://financialtimes.atlassian.net/browse/ACQ-1330)

ACQ-1330 explicitly install npm 7 for github pages deployment

---

.circleci/config.yml

remove useless circleci npm update helper, we use package-lock
https://financialtimes.atlassian.net/browse/ACQ-1442

ACQ-1442: remove useless circleci npm update helper, we use package-lock

---

components/__snapshots__/password.spec.js.snap
components/password.jsx

Changes the password label to “Use 8 or more characters. You can use letters, numbers or symbols”
https://financialtimes.atlassian.net/browse/ACQ-1418
|    ![before](https://user-images.githubusercontent.com/1725956/155523578-c59fa626-85bf-43fc-ab6e-f7833279f14e.png)    |   ![after](https://user-images.githubusercontent.com/1725956/155523667-d48ad83e-b947-45ef-8c8e-ae999b4ae029.png)     |

Clarify password validation label

---

utils/zuora.js

Context 3DS recurring payment are declined for Amex users.
See: https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/LA_Hosted_Payment_Pages/B_Payment_Pages_2.0/H_Integrate_Payment_Pages_2.0
https://financialtimes.atlassian.net/browse/ACQ-1526

ACQ-1526: add americanExpress to zuora setAgreement call

---

.circleci/config.yml

copied from: https://github.com/Financial-Times/n-membership-sdk/pull/536
Ticket:
https://financialtimes.atlassian.net/browse/ACQ-1529

ACQ-1529: add npm-publish-token to cirlceci config

---

components/accept-terms.jsx
main.scss

Horizontal Divider before accepting terms checkbox. 
Use isNewDigitalBuyFlowConsent flag to hide policy when the flag is on.
https://financialtimes.atlassian.net/browse/ACQ-1472

Horizontal Divider before accept terms checkbox

---

.circleci/config.yml
components/position.jsx
components/position.spec.js
components/responsibility.jsx
components/responsibility.spec.js
package-lock.json
package.json

We're working towards making a change to the signup forms users see when they join under a B2B licence to capture information about the position and responsibility they hold within their company in more depth. This will result in more accurate and actionable data; for more detail see [the Access & Identity ticket](https://financialtimes.atlassian.net/browse/AIM-761).
In order to achieve this, we've added new data sets to `n-common-static-data`. The [PR for that work is here](https://github.com/Financial-Times/n-common-static-data/pull/36). This means there are now [two sets of data](https://docs.google.com/spreadsheets/d/1sLMcknLOHiA5DzNcLJD3I_7TkBo0wTIKQn_13RMgEfg/edit#gid=755191669) for the `position` and `responsibility` fields; one for B2C and one for B2B.
This PR updates the fields …

ENT-561 Add B2B Options to Position and Responsibility Fields

---

components/responsibility.jsx

Currently the `isB2B` prop defaults to `false` on the `Responsibility` component and `true` on the `Position` field, which isn't great for consistency. This PR changes the prop to default to `false` on both components.
[ENT-561](https://financialtimes.atlassian.net/jira/software/projects/ENT/boards/1312?selectedIssue=ENT-561)

ENT-561 Correct isB2B Responsibility Component Default

---

components/__snapshots__/payment-type.spec.js.snap
components/payment-type.jsx

The input checkbox for `payFasterNextTime` was causing the iframe to reload everytime it was clicked one. The input needs to go outside of the main div in order for this not to happen.
[JIRA](https://financialtimes.atlassian.net/jira/software/c/projects/ACC/boards/1461?modal=detail&selectedIssue=ACC-1581)
Before:
https://user-images.githubusercontent.com/10453619/164730814-f9e6a8af-3b18-452a-9669-280e403bfb6c.mov
After:
https://user-images.githubusercontent.com/10453619/164729647-882db70a-20c2-4abe-bbce-4520f10b0421.mov

ACC-1581 Fix payFasterNextTime reload iframe bug

---

components/__snapshots__/registration-confirmation.spec.js.snap
components/registration-confirmation.jsx
styles/confirmation.scss

Adds store links to the confirmation page
https://financialtimes.atlassian.net/browse/ACQ-1505
* social links still show black on storybook, nothing to do with this, works fine on next-subscribe

ACQ-1505: Adds store links to confirmation page

---

.github/workflows/gh-pages-deploy.yml

I don't how to test this other than trying it directly. 
It should prevent all these failed runs:
https://app.circleci.com/pipelines/github/Financial-Times/n-conversion-forms?branch=gh-pages&filter=all
Based on adding `[ci skip]` to the commit message: https://discuss.circleci.com/t/gh-pages-not-being-ignored/26062/2
That is generated on this action: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-set-custom-commit-message
No ticket

skip ci for gh-pages deploy

---

styles/payment-term.scss

Skip a line for the subtitle by changing the CSS of the` __subtitle` subclass in the paymentTerm component.
[JIRA](https://financialtimes.atlassian.net/jira/software/c/projects/ACC/boards/1461?modal=detail&selectedIssue=ACC-1714)
before: 
after:

ACC-1714 Fix subtitle position for paymentTerm component

---

components/__snapshots__/registration-confirmation.spec.js.snap
components/registration-confirmation.jsx

Change the wording from `Finish` to `Start reading` in the registration confirmation cta.
https://financialtimes.atlassian.net/browse/ACQ-1736

Change registration confirmation cta label

---

components/__snapshots__/delivery-instructions.spec.js.snap
components/delivery-instructions.jsx

We need to update the copy on the delivery instructions for CEMEA and APAC. [These are the instructions for CEMEA](https://docs.google.com/document/d/15m79euirAZQ3Y837x-XyqCaalh6VcHlT/edit), We don’t have instructions for APAC, so we’ll use this one for now
[TICKET](https://financialtimes.atlassian.net/browse/ACC-1803)

ACC-1803: update delivery instructions for emea and apac

---

components/delivery-address-map.jsx
components/delivery-address-type.jsx
utils/delivery-option-messages.js
utils/delivery-option-messages.spec.js

*Show the correct delivery options for CEMEA and APAC regions (adding the Mail Delivery option in this PR).
*Make the delivery type (home, company, pobox) non-editable in edit mode.
[JIRA](https://financialtimes.atlassian.net/jira/software/c/projects/ACC/boards/1461?modal=detail&selectedIssue=ACC-1807)
[JIRA](https://financialtimes.atlassian.net/jira/software/c/projects/ACC/boards/1461?modal=detail&selectedIssue=ACC-1810)

ACC-1807 ACC-1810 Show correct options for delivery-option.jsx component

---

components/licence-confirmation.jsx
package-lock.json

Our aim with this ticket is to direct the user to Workspace once they have completed the sign up form by amending the button's text and link on the Confirmation page.
We amended the button in the LicenseConfirmation.jsx page  and passed in content from the next-subscribe repo so that we  could clearly separate what information will be passed to b2b and US users in the logic for the button (which lives in next-subscribe).
We have passed in a BodyContent prop that contains a react element with text in that will differ depending on whether the user is based in the US or belongs to the b2b cohort.  If neither is true then we show the default text that was already in the LicenseConfirmation component. 
[https://financialtimes.atlassian.net/browse/ELE-79?atlOrigin=eyJpIjoiNzIxOTZjOWNhODUwNGM3MDh …

Added property to allow hiding of myFT paragraph on b2b confirmation page

---

components/__snapshots__/licence-header.spec.js.snap
components/__snapshots__/licence-title.spec.js.snap
components/licence-header.jsx
components/licence-title.jsx
main.scss

Adds a logo to the licence header. Also aligns title to the left as per request: https://financialtimes.slack.com/archives/C03NJHLTY7P/p1658925951790209?thread_ts=1658923616.759849&cid=C03NJHLTY7P
https://financialtimes.atlassian.net/browse/ACQ-1767
|![Screenshot 2022-07-27 at 15 16 36](https://user-images.githubusercontent.com/1725956/181256371-6ad69dcd-1419-4e71-b4b2-fc6b5f175bfa.png)|![Screenshot 2022-07-27 at 15 16 19](https://user-images.githubusercontent.com/1725956/181256385-7ad8a204-67c0-4241-acaf-d6b975fe8be1.png)|

Adds logo to the licenses

---

utils/payment-type.js

as part of this ticket [ACQ-1643]([ACQ-1643](https://financialtimes.atlassian.net/browse/ACQ-1643)) we need to create a new client method hidePanel on payment type because in the client side we need to show paypal as unique option in case of an error configuring the payment gateway
[ACQ-1643]([ACQ-1643](https://financialtimes.atlassian.net/browse/ACQ-1643))

ACC-1643: add hide panel method for payment type

---

utils/delivery-option-messages.js
utils/form-element.js

Adding new delivery option message for CEMEA regions, when flight market is false.
Original ticket: https://financialtimes.atlassian.net/browse/PTRM-1819
Tracking on Acquisition board https://financialtimes.atlassian.net/browse/ACQ-1861

ACQ-1861: Add new copy when flight market is false

---

package.json

Our shared library n-conversion-forms has n-pricing in devDependencies. Not sure how it got there since it is a hard dependency and it needs to be installed for it to work. 
It should go to dependencies (or maybe peerDependencies), otherwise any app using n-conversion-forms that doesn’t have n-pricing as well will inexplicably fail in weird ways.
[Ticket](https://financialtimes.atlassian.net/browse/ACQ-1980)

ACC-1980: change dev dependency to dependency

---

components/__snapshots__/payment-type.spec.js.snap
components/accept-terms.jsx
components/accept-terms.stories.js
components/payment-type.jsx
components/payment-type.spec.js
components/payment-type.stories.js
utils/payment-type.js

The following PR includes 2 changes. Both are required for the implementation of allowing Bank Transfer payments to be accepted within Next-Retention. 
1. Adds a `banktransfer` to option to the Payment Types, with the props `enableBankTransfer` 
2. Adds a `deferredBilling` to the Accept Terms, with the props `isDeferredBilling`
[ACC-2075](https://financialtimes.atlassian.net/browse/ACC-2075?atlOrigin=eyJpIjoiMTFlNjY1MzVlY2E1NDViOGIyN2U5ZDNmODY3ODkzODEiLCJwIjoiaiJ9)
|        |   <img width="914" alt="Screenshot 2022-11-16 at 14 32 39" src="https://user-images.githubusercontent.com/40343797/202213378-5ceedac6-3375-4fdb-825f-edef5ab3bbd6.png">    |
|        |   <img width="919" alt="Screenshot 2022-11-16 at 14 33 30" …

Acc 2075 banktransfer payment type

---

package-lock.json
package.json

The First Party Data programme (FPDP) have been working on standardising the FPD data they collect from users on [FT.com](http://ft.com/) B2C, [FT.com](http://ft.com/) B2B and FT Live businesses.
The first part of the standardisation is the Job Position field. This PR updates some of the fields and also add new fields to be consistent with other apps
[Jira Ticket](https://financialtimes.atlassian.net/browse/ACC-2067)

ACC-2067-chore: Bumping up n-common-static-data version

---

components/__snapshots__/graduation-date.spec.js.snap

The years we show to users changed on 1 Jan 2023, so the snapshot needed updating
I reran the tests to create a new snapshot, so that the tests pass (and the nightly build will no longer fail :) )

update snapshot to correct available dates

---

components/__snapshots__/graduation-date.spec.js.snap
helpers/billing-countries.js
helpers/demographics.js
helpers/index.js
helpers/index.spec.js
package-lock.json
package.json

This PR refactors the piece of code we are using in `next-profile` from `n-common-static-data` package for demographic form, country form & your organisation form in `next-profile` so that we could get rid of the `n-common-static-data`  completely from `next-profile` for better consistency and a single source of truth which would help us also avoid issues like [this one here](https://financialtimes.slack.com/archives/CSVRXFV6F/p1670504977875609). 
This PR also added some tests for the helpers that were not added.
[Jira ticket](https://financialtimes.atlassian.net/browse/ACC-2134)

ACC-2134-common static data migration

---

helpers/billing-countries.js
helpers/demographics.js

This PR is a fix that changes the imports in billing-countries and demographics helpers to require because it's failing on consuming apps.
[Jira ticket](https://financialtimes.atlassian.net/browse/ACC-2134)

ACC-2134-fix: change import to require in bill-countries and demographics helpers

---

components/__snapshots__/accept-terms.spec.js.snap
components/__snapshots__/graduation-date.spec.js.snap
components/accept-terms.jsx
components/accept-terms.stories.js
package-lock.json
styles/accept-terms.scss

- Add optional children to render between Policies and Cookies text and Accept Terms checkbox. 
- Add `privacyPoliciesPosition` prop to choose if Policies and Cookies text should go in top or bottom (defaults to top).
EDIT: Changed images to reflect request by Ludo.
- https://financialtimes.atlassian.net/browse/ACQ-2077
| Without children | 
| ------ |
|   ![image](https://user-images.githubusercontent.com/22417566/212907233-8d0b00a2-bbe5-4a85-8c83-53d9ad1651f4.png)    |
|  `privacyPoliciesPosition` top |  `privacyPoliciesPosition` bottom | 
| ----- | ----- |  
|  ![image](https://user-images.githubusercontent.com/22417566/214045308-e2118bd3-25a2-4274-a337-10f7e671dbe7.png)   | ![image](https://user-images.githubusercontent.com/22417566/214045407-1c72eee0-dc84-4676-a0ce-1ddbec50e043.png) …

feat: add optional children and policies position to accept-terms

---

helpers/billing-countries.js
helpers/demographics.js

This PR is a fix that changes the exports in billing-countries and demographics helpers to module.exports because it's failing on consuming apps.
PS: I hate to keep having a do-over 😟
[Jira ticket](https://financialtimes.atlassian.net/browse/ACC-2134)

ACC-2134-fix: change exports to use module.export

---

package-lock.json
package.json
utils/validation.js
utils/validation.spec.js

- refactor: refactor validation to make it easier to pass formOptions to origami forms
- feat: update o-forms
**NOTE**: This change will only affect next-subscribe in https://github.com/Financial-Times/next-subscribe/blob/4ccd86829f9001309b6c10073139ec94b16b7eca/client/controller.js#L33. A PR is coming in that file after this is released.

ACQ-2116: fix captcha in next subscribe to trigger after client validation

---

components/__snapshots__/billing-country.spec.js.snap
components/__snapshots__/country.spec.js.snap
components/billing-country.jsx
components/billing-country.spec.js
components/country.jsx
components/country.spec.js

Note that there should be no visual changes that should've occurred here.
Summary: We make `BillingCountry` use `Country` as a shallow wrapper around it to prevent duplication.
We also remove classes `js-field__input`, `js-item__value` and `js-unknown-user-field` since I can't see them as a CSS in our codebase:
https://github.com/search?q=repo%3AFinancial-Times%2Fn-conversion-forms+js-field__input&type=code
https://github.com/search?q=repo%3AFinancial-Times%2Fn-conversion-forms+js-item__value&type=code
https://github.com/search?q=repo%3AFinancial-Times%2Fn-conversion-forms+js-unknown-user-field&type=code
https://financialtimes.atlassian.net/browse/ACQ-2147

ACQ-2147 Refactor Country and BillingCountry

---

.circleci/config.yml

Following the footsteps of https://github.com/Financial-Times/n-membership-sdk/pull/623
Difference is, we don't have varying node versions so we just straight up install node version v7.
https://financialtimes.atlassian.net/browse/ACQ-2174

ACQ-2174 Replace node-orb with npm global install

---

components/__snapshots__/b2c-partnership-confirmation.spec.js.snap
components/b2c-partnership-confirmation.jsx
components/b2c-partnership-confirmation.spec.js

Make `Welcome to your Premium access` label dynamic based on licence product code.
Add `productCode` to `props` to change label.
Values
- p1 or P1 - Standard
- any other value - Premium
https://financialtimes.slack.com/archives/C052K8ARM9A/p1685958677283739
|![image](https://github.com/Financial-Times/n-conversion-forms/assets/110386755/8bb0e428-5010-4ceb-89cf-8c63aa04093e)|<img width="1176" alt="image" src="https://github.com/Financial-Times/n-conversion-forms/assets/110386755/a7e7e4d4-df97-44f2-8158-a20f53a1cc61">|

add dynamic access label to b2c-partnership-confirmation

---

components/__snapshots__/b2c-partnership-confirmation.spec.js.snap
components/b2c-partnership-confirmation.jsx
components/b2c-partnership-confirmation.spec.js

Add ePaper to B2C partnership licence confirmation component
Change default welcome text
Old `Welcome to your Premium access`
New `Welcome to your FT access`
[Slack](https://financialtimes.slack.com/archives/C052K8ARM9A/p1686659166680829?thread_ts=1686647251.963659&cid=C052K8ARM9A)
|ePaper|<img width="1091" alt="image" src="https://github.com/Financial-Times/n-conversion-forms/assets/110386755/e212a27e-2e8e-478c-af8d-89690bd237a8">|
|default |<img width="992" alt="image" src="https://github.com/Financial-Times/n-conversion-forms/assets/110386755/cd0628fc-9cd6-4637-ab51-35bdba143e91">|

add ePaper to b2c-partnership-confirmation

---

components/payment-term.jsx
utils/payment-term.js
utils/payment-term.spec.js

[ACQ-2228](https://financialtimes.atlassian.net/browse/ACQ-2228) is big enough to split the story into multiple PRs.
**PART 1**: convert paymentTerms response from a regular array to a indexed collection by using an object to contain them.
Before:
```Javascript
const paymentTerms = [
{ name: 'annual', value: 'P1Y' },
{ name: 'quarterly', value: 'P3M' },
];
// if looking for a specific term --> paymentTerms.find(term => term.value === 'P3M')
```
After:
```Javascript
const paymentTerms = {
P1Y: { name: 'annual', value: 'P1Y' },
P3M: { name: 'quarterly', value: 'P3M' },
};
// if looking for a specific term --> paymentTerms['P3M']
```
[ACQ-2228]: https://financialtimes.atlassian.net/browse/ACQ-2228?atlOrigin=eyJpIjoiNWRkNTl …

ACQ-2228: converting paymentTerms from an array to an "indexed" collection (by an object)

---

components/__snapshots__/accept-terms.spec.js.snap
components/accept-terms.jsx
components/accept-terms.spec.js
components/accept-terms.stories.js
styles/accept-terms.scss

By adding Policies Text in Sign up forms isRegister and isAuthFirstAccount props names don’t make sense anymore. 
We need to check use cases and change their names and/or coding.   
Note: This ticket is not only meant to those 2 props. We should check the entire component and do refactors where needed. At the moment the component is filled with boolean props and rendering several different components that we are not sure which ones are being used and if others should be merged with each other. 
If any doubt check with Product for text definitions.
(https://financialtimes.atlassian.net/browse/ACQ-2088)
Document to clarify how accept terms is used and variables that we are not using.
https://docs.google.com/document/d/1RkanlvYZoSafEt4Oeg2TidhFy9qNx6R52T9dW6sqeLg/edit 
Have you completed …

ACQ-2088 refactor accept terms component for next subscribe sign up forms

---

Makefile

I ran the command `make run` (which in turn calls `npm run storybook`) with the intention of running Storybook to develop a confirmation component and encountered:
```
Note — An .env file exists. Its contents have been exported as environment variables.
npm run storybook
> @financial-times/n-conversion-forms@0.0.0 storybook
> start-storybook -p 5005
info @storybook/react v6.5.16
info
info => Loading presets
info Addon-docs: using MDX1
info => Using implicit CSS loaders
(node:10658) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.
See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for …
```

Re-enable Storybook for Node.js v18

---

secret-squirrel.js

[secret-squirrel](https://github.com/Financial-Times/secret-squirrel) is deprecated but while it remains in usage by this repo and is compatible with my operating system, my commits are being blocked by the presence of `addressLine3MaxLength`.
This PR adds that value to the list of `denyOverrides` in `secret-squirrel.js` to avoid this from happening.
N/A
N/A

Modify secret-squirrel.js

---

components/__snapshots__/package-change.spec.js.snap
components/accept-terms-subscription.jsx
components/index.jsx
components/package-change.jsx
components/package-change.spec.js
components/package-change.stories.js
components/payment-term.jsx
components/payment-term.spec.js
components/payment-term.stories.js
components/seven-day-pass-experiment-confirmation.jsx
components/seven-day-pass-experiment-confirmation.stories.js

RS-310
This PR updates various parts of the n-conversion-forms and adds a new component to facilitate the subscribe journey for a 7-day pass.
The 7-day pass is an experiment to gauge user's propensity to pay for a single-term 7-day pass to FT content. However, it is currently not possible to create such an offer and corresponding subscription.
Therefore we will be presenting the offer as granting 7 days' access and upon payment will reveal to the user that they have actually been granted one month's access (lucky them!). In the background (in work done in next-subscribe), the subscription will be cancelled to prevent recurring payments, thereby creating the illusion of a single-term subscription. 
These changes are **short-term** — they will be reverted on/around 11 Sep 2023 because this …

RS-310 Apply changes for 7-day pass experiment

---

.github/workflows/gh-pages-deploy.yml

This PR fixes the failing deployment of Storybook owing to its usage of `make install` — see: https://github.com/Financial-Times/n-conversion-forms/actions/runs/6049500710/job/16420507328
```
Run make install
make: *** No rule to make target 'install'.  Stop.
Error: Process completed with exit code 2.
```
The `make` commands were removed in the previous PR, which migration this app to dotcom-tool-kit: https://github.com/Financial-Times/n-conversion-forms/pull/752
N/A
N/A

Fix deployment of Storybook in CI workflow

---

.github/workflows/gh-pages-deploy.yml

This PR https://github.com/Financial-Times/n-conversion-forms/pull/753 attempted to fix the deployment of Storybook, though it did not fail owing to this error: https://github.com/Financial-Times/n-conversion-forms/actions/runs/6071085286/job/16468398553.
This [Stack Overflow question](https://stackoverflow.com/questions/72866798/node-openssl-legacy-provider-is-not-allowed-in-node-options) indicates that upgrading to Node.js v18 with npm v9 and retaining `NODE_OPTIONS=--openssl-legacy-provider` in the command worked for them so I figure it is worth a try.
N/A
N/A

Upgrade Node.js version used in Storybook deployment

---

components/__snapshots__/confirmation.spec.js.snap
components/confirmation.jsx
components/confirmation.spec.js
components/confirmation.stories.js

RS-275
This PR allows the `Confirmation` component to receive a `newsletterScheduleExplainer` prop, which is a node that contains text like the below when the user subscribes to an email newsletter product:
> You will receive your first newsletter on the next weekday to n-conversion-forms@1694502556888@ftqa.org.
- [RS-275: Modifications to next-subscribe payment flow](https://financialtimes.atlassian.net/jira/software/c/projects/RS/boards/1547?modal=detail&selectedIssue=RS-275)
- https://github.com/Financial-Times/next-subscribe/pull/2630
N.B. The offer names will be changed upstream, meaning the text displayed will be subject to the following changes:
- "Niches Standard 1 - Inside Politics" -> "Inside Politics email newsletter"
- "Niches Premium 1 - Unhedged" -> "Unhedged email …

Apply changes for email newsletter products

---

components/__snapshots__/delivery-option.spec.js.snap
utils/delivery-option-messages.js
utils/delivery-option-messages.spec.js

Hello, could someone confirm whether the displayName field value is used for anything on the MMA (perhaps in the Delivery Address tab) from the following endpoint:
https://api.ft.com/newspaper/fulfilment/options
We have a request to change the value from "displayName": "Home Delivery" to "displayName": "Hand Delivery"
As a result on the acq side => print flow - delivery step - the “Home delivery” option will now be called “Hand delivery”. 
https://financialtimes.slack.com/archives/CSVRXFV6F/p1694762784250909
(https://financialtimes.atlassian.net/browse/ACQ-2398)

ACQ-2398: Change: Home delivery to Hand delivery 

---

.eslintignore
components/__snapshots__/delivery-option.spec.js.snap
components/accept-terms-subscription.stories.js
secret-squirrel.js
utils/delivery-option-messages.js

Remove Covid information on the Paper Vouchers
https://financialtimes.atlassian.net/browse/ACQ-2416

ACQ-2416: Remove Covid information on the Paper Vouchers

---

components/__snapshots__/package-change.spec.js.snap
components/accept-terms-subscription.jsx
components/index.js
components/package-change.jsx
components/package-change.spec.js
components/package-change.stories.js
components/payment-term.jsx
components/payment-term.spec.js
components/payment-term.stories.js
components/seven-day-pass-experiment-confirmation.jsx
components/seven-day-pass-experiment-confirmation.stories.js

RS-318
The Subscriber Growth team is running another 7-day pass experiment.
The first experiment targeted lapsed triallists (£1 for 4-weeks who cancelled before the automatic transition to a full subscription) and offered them a 7-day single-term subscription for £1.99 (which because of system limitations was actually a 30-day single-term subscription).
This second experiment will target anonymous users and offer them the same 7-day (actually 30-day) single-term subscription, but at £4.99 (the higher price has been recommended because the audience is higher risk and likely has a higher willingness to pay).
This is to give us a better overall picture of how a 7-day trial can be most effectively offered in the long-term.
We require this experiment to run for a minimum of 22 days, as we …

Apply changes for 7-day pass experiment v2

---

package-lock.json
package.json

This PR upgrades the `@dotcom-tool-kit/component` package so as to fix the auto-publish mechanism for new releases, as described by @joelcarr's [Slack post](https://financialtimes.slack.com/archives/C041V9QA7/p1699872520305709?thread_ts=1697197538.720119&cid=C041V9QA7).
This will allow release [v32.3.0](https://github.com/Financial-Times/n-conversion-forms/releases/tag/v32.3.0) to be published, which in turn needs to be consumed by this next-subscribe PR https://github.com/Financial-Times/next-subscribe/pull/2667 in order to begin the 7-day trial experiment v2.
N/A
N/A

Upgrade @dotcom-tool-kit/component ^4.0.3 -> ^4.0.4

---

package-lock.json
package.json

Bump n-common-static-data to include the following changes:
https://github.com/Financial-Times/n-common-static-data/releases/tag/v2.2.0
- positions lists should replicate what FT Core uses: https://github.com/Financial-Times/memb-common-value-types/blob/master/src/main/resources/demographics/position.json
- removed legacy code used by swg (disabled years ago)
This change is needed to fix a production issue: https://financialtimes.slack.com/archives/CSVRXFV6F/p1701691948640919
https://financialtimes.atlassian.net/browse/ACQ-2495

ACQ-2495: bump n-common-static-data

---

components/__snapshots__/confirmation.spec.js.snap
components/confirmation.jsx
components/confirmation.spec.js
components/confirmation.stories.js

This PR is an extension of https://github.com/Financial-Times/n-conversion-forms/pull/771 after it was noticed there are some aspects of the confirmation page that requires the text amended to reflect single-term subscriptions.
- [RS-510: Finance course user sign-up journey](https://financialtimes.atlassian.net/jira/software/c/projects/RS/boards/1547?selectedIssue=RS-510)
- https://github.com/Financial-Times/next-subscribe/pull/2723
Compare the last paragraph.
|![before](https://github.com/Financial-Times/n-conversion-forms/assets/10484515/77a25aa0-4aa5-4d3b-90c8-65d53c88a146)|![after](https://github.com/Financial-Times/n-conversion-forms/assets/10484515/a4db9081-86d2-44a1-be09-208635468f77)|
Have you completed these common tasks (remove those that …

Accommodate 'Termed' subscriptionTermType (II)

---

.gitignore

The folder `.toolkitstate` created by `dotcom-tool-kit` is added to gitignore
[ACQ-2523](https://financialtimes.atlassian.net/browse/ACQ-2523)
[ACQ-2523]: https://financialtimes.atlassian.net/browse/ACQ-2523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACQ-2523: adding .toolkitstate to gitignore

---

components/__snapshots__/industry.spec.js.snap
components/__snapshots__/position.spec.js.snap
components/__snapshots__/responsibility.spec.js.snap
components/industry.jsx
components/industry.stories.js
components/position.jsx
components/position.stories.js
components/responsibility.jsx
components/responsibility.stories.js
package-lock.json
package.json

This ticket focuses on syncing `n-common-static-data` lists with FT Core.
The following actions were taken:
- sorted `industry`, `position` and `responsibility` lists for better UI display
- created `Default` stories for `industry`, `position` and `responsibility` in Storybook
- updated `n-common-static-data` dependency (v2.3.1 tag)
- update test snapshots
[ACQ-2528](https://financialtimes.atlassian.net/browse/ACQ-2528)
[ACQ-2528]: https://financialtimes.atlassian.net/browse/ACQ-2528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACQ-2528: synced n-static-common-data lists with FT Core

---

.github/PULL_REQUEST_TEMPLATE.md

This PR adds an additional field to the PR template so that the contributor is prompted to say which release type they propose for their changes.
This can sometimes be a discussion point and so is worth bringing it to these conversation starters rather than it being an afterthought once the changes and code itself has been approved (as has happened here: https://github.com/Financial-Times/n-conversion-forms/pull/799#issuecomment-2205777590).
N/A
N/A

Upate GitHub Pull Request template

---

components/delivery-option.jsx
components/delivery-option.stories.js
utils/delivery-option-messages.js
utils/delivery-option-messages.spec.js

This PR changes the delivery message displayed for Japan.
[ACQ-2876](https://financialtimes.atlassian.net/browse/ACQ-2876)
|![old](https://github.com/Financial-Times/n-conversion-forms/assets/25990506/75024813-66b2-4839-944b-483bd62fba62)|![new](https://github.com/Financial-Times/n-conversion-forms/assets/25990506/fe1ef763-1aaa-484d-a884-9dcb402025b5)|
[ACQ-2876]: https://financialtimes.atlassian.net/browse/ACQ-2876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACQ-2876: changed delivery message for Japan

---

components/__snapshots__/delivery-option.spec.js.snap
components/delivery-option.jsx
styles/_shared.scss
utils/delivery-option-messages.js
utils/delivery-option-messages.spec.js

This PR focuses on not displaying a delivery option title if the `title` property is not provided. In this case, `Japan` will not have a title for all delivery messages.
Tests were also updated to reflect this change.
[ACQ-2876](https://financialtimes.atlassian.net/browse/ACQ-2876)
|![new](https://github.com/user-attachments/assets/20b494bc-0790-4946-ac0b-39b779318eaf)|![new](https://github.com/user-attachments/assets/fdcfa788-2be2-4b39-9e71-8a5b1555a1b2)|
[ACQ-2876]: https://financialtimes.atlassian.net/browse/ACQ-2876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACQ-2876: delivery option title not displayed if property not provided and test updates

---

components/__snapshots__/delivery-start-date.spec.js.snap
components/delivery-start-date.jsx
utils/delivery-option-messages.js
utils/delivery-option-messages.spec.js

This PR changes the following labels on `delivery` step:
- `Delivery Start Date` to `Start Date`
- `Earliest available delivery date:` to `The first print edition you will receive is:`
- One of the delivery messages had a typo:
- `our digital replica of the each daily edition` to `our digital replica of each daily edition`
Tests were also updated.
[ACQ-2891](https://financialtimes.atlassian.net/browse/ACQ-2891)
|![old](https://github.com/user-attachments/assets/7aca010b-7dfc-4ce6-8708-25010a9e7972)|![new](https://github.com/user-attachments/assets/9f93779a-f53a-44b2-b003-14e0d14834e9)|
[ACQ-2891]: https://financialtimes.atlassian.net/browse/ACQ-2891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …

ACQ-2891: changed labels on delivery step and updated tests
